TEXT={}
TEXT[211,'nl']=[
'Stof:','Lichte zomerstof met een geweven uitstraling; de exacte vezelsamenstelling was niet zichtbaar in het aangeleverde bewijsmateriaal.',
'Voor het gezin:','Een vrolijke tanktop voor moeder en dochter, voor stranduitjes, vakantiefoto’s in een resort en zonnige gezinsdagen.',
'Print:','Scarlet Ruffle is een felrode tanktop met ruches. Broeken, andere onderstukken en accessoires zijn niet inbegrepen.',
'Ontwerpdetails:','Verstelbare schouderbandjes en zachte, gelaagde ruches vormen een gemakkelijk te dragen top voor warm weer.',
'Wasvoorschrift:','Machinewas koud op een fijnwasprogramma, aan de lijn drogen, niet bleken en zo nodig binnenstebuiten op lage temperatuur strijken.',
'Maatbereik:','Kind 3 jaar tot en met Kind 9-10 jaar en Moeder S-M, volgens de bijgevoegde maattabel van de leverancier.',
'Maattabel - Tanktop','Maat','Leeftijd','Lichaamslengte (cm/in)','Verstelbaar bandje (cm/in)','Zoom/opening van het lijfje (cm/in)',
'Scarlet Ruffle is gemaakt voor vrolijke momenten samen als moeder en dochter, van strandfoto’s tot brunches bij warm weer en vakantiewandelingen. De felrode tanktop met ruches vormt het stralende middelpunt en is gemakkelijk te combineren met je eigen shorts, rokken of broeken.',
'Dit product omvat alleen de tanktop. De maattabel gebruikt de aangeleverde afmetingen voor de bandjes en de opening; ontbrekende waarden voor borst, heupen en totale kledinglengte worden bewust niet geschat.',
'Belangrijkste kenmerken:','Alleen de tanktop:','Omvat de rode top met ruches; onderstukken en andere kledingstukken voor de styling op de foto’s zijn niet inbegrepen.',
'Maten voor moeder en dochter:','Bevat alleen rijen voor meisjes en moeders waarvoor de maattabel van de leverancier afmetingen vermeldt.',
'Verstelbare bandjes:','De afmetingen van de bandjes zijn overgenomen uit de bijgevoegde maattabel.',
'Camisolemodel met ruches:','Felrode, gelaagde ruches geven een zomerse stijl die mooi uitkomt op foto’s.',
'Gemakkelijk te combineren:','Draag de top met je eigen strandbroek, denim shorts, rok of andere basisstukken voor de vakantie.',
'Kies elke maat afzonderlijk en stel een bijpassende rode moeder-dochterlook samen voor jullie volgende zonnige dag.'
]
TEXT[211,'pl']=[
'Materiał:','Lekki letni materiał o wyglądzie tkaniny; dokładny skład włókien nie był widoczny w dostarczonych materiałach źródłowych.',
'Rodzinny styl:','Wyrazisty top na ramiączkach dla mamy i córki, idealny na plażę, zdjęcia z wakacji w kurorcie i słoneczne dni z rodziną.',
'Wzór:','Scarlet Ruffle to intensywnie czerwony top na ramiączkach z falbanami. Spodnie, inne dolne części stroju i dodatki nie są wliczone.',
'Szczegóły fasonu:','Regulowane ramiączka i miękkie, warstwowe falbany tworzą swobodny top na ciepłe dni.',
'Pielęgnacja:','Prać w pralce w zimnej wodzie na delikatnym programie, suszyć rozwieszone, nie wybielać i w razie potrzeby prasować na lewej stronie w niskiej temperaturze.',
'Zakres rozmiarów:','Dziecko 3 lata do Dziecko 9-10 lat oraz Mama S-M według załączonej tabeli rozmiarów dostawcy.',
'Tabela rozmiarów - Top na ramiączkach','Rozmiar','Wiek','Wzrost (cm/in)','Regulowane ramiączko (cm/in)','Dół/otwór korpusu topu (cm/in)',
'Scarlet Ruffle powstał z myślą o radosnych chwilach mamy i córki: zdjęciach na plaży, brunchach w ciepłe dni i wakacyjnych spacerach. Intensywnie czerwony top z falbanami stanowi wyrazisty akcent, a przy tym łatwo go zestawić z własnymi szortami, spódnicami lub spodniami.',
'Oferta obejmuje wyłącznie top na ramiączkach. Tabela rozmiarów wykorzystuje dostarczone wymiary ramiączek i otworu; niedostępne wartości dla biustu, bioder i całkowitej długości odzieży celowo nie są szacowane.',
'Najważniejsze cechy:','Tylko top na ramiączkach:','Obejmuje czerwony top z falbanami; dolne części stroju i elementy stylizacji widoczne na zdjęciach nie są wliczone.',
'Rozmiary dla mamy i córki:','Uwzględniono wyłącznie wiersze dla dziewczynek i mam, dla których tabela dostawcy podaje wymiary.',
'Regulowane ramiączka:','Wymiary ramiączek przepisano z załączonej tabeli rozmiarów.',
'Fason topu na ramiączkach z falbanami:','Intensywnie czerwone, warstwowe falbany tworzą letni styl, który pięknie wygląda na zdjęciach.',
'Łatwe zestawianie:','Połącz top z własnymi spodniami plażowymi, dżinsowymi szortami, spódnicami lub wakacyjnymi ubraniami bazowymi.',
'Wybierz każdy rozmiar osobno i stwórz pasujący czerwony strój dla mamy i córki na kolejny wspólny słoneczny dzień.'
]
TEXT[211,'pt-BR']=[
'Tecido:','Tecido leve de verão com aparência de trama plana; a composição exata das fibras não estava visível nas evidências fornecidas.',
'Estilo em família:','Uma regata vibrante para mãe e filha, feita para passeios na praia, fotos no resort e dias ensolarados em família.',
'Estampa:','Scarlet Ruffle é uma regata vermelho-vivo com babados. Calças, outras peças de baixo e acessórios não estão incluídos.',
'Detalhes do modelo:','Alças ajustáveis e babados suaves em camadas criam uma blusa prática para os dias quentes.',
'Cuidados:','Lave à máquina com água fria no ciclo delicado, seque no varal, não use alvejante e, se necessário, passe do avesso em temperatura baixa.',
'Grade de tamanhos:','Criança 3 anos a Criança 9-10 anos e Mãe S-M, conforme a tabela do fornecedor em anexo.',
'Tabela de medidas - Regata','Tamanho','Idade','Altura (cm/in)','Alça ajustável (cm/in)','Barra/abertura do corpo da peça (cm/in)',
'Scarlet Ruffle foi feita para momentos alegres entre mãe e filha, de fotos na praia a brunches nos dias quentes e passeios de férias. A regata vermelho-vivo com babados é o destaque do visual e combina facilmente com seus próprios shorts, saias ou calças.',
'Este anúncio inclui apenas a regata. A tabela utiliza as medidas fornecidas das alças e da abertura; os valores indisponíveis de busto, quadril e comprimento total da peça não são estimados propositalmente.',
'Principais características:','Somente a regata:','Inclui a blusa vermelha com babados; as peças de baixo e os itens de composição do visual nas fotos não estão incluídos.',
'Tamanhos para mãe e filha:','Inclui apenas as linhas de meninas e mães para as quais a tabela do fornecedor apresenta medidas.',
'Alças ajustáveis:','As medidas das alças foram copiadas da tabela de medidas em anexo.',
'Modelo de blusa de alças com babados:','Babados vermelho-vivo em camadas criam um estilo de verão pronto para as fotos.',
'Fácil de combinar:','Use com suas próprias calças de praia, shorts jeans, saias ou peças básicas de férias.',
'Escolha cada tamanho para montar um visual vermelho combinando entre mãe e filha para o próximo dia ensolarado juntas.'
]
TEXT[213,'nl']=[
'Stof:','95% katoen, op basis van de geverifieerde productgegevens.',
'Voor het gezin:','Een sportief, bijpassend T-shirt voor moeders, vaders, meisjes en jongens, geschikt voor ontspannen uitjes, dagen in het park, verjaardagen en gezinsfoto’s.',
'Printreferentie:','Red Heart Raglan combineert een wit T-shirtlijf met contrasterende rode mouwen, strepen op de mouwen en een klein hartdetail.',
'Ontwerpdetails:','Korte mouwen, ronde hals, een ontspannen raglanmodel en dezelfde rood-witte kleurcombinatie voor kinderen, moeders en vaders. Rokken, shorts, schoenen, zonnebrillen en buitenrekwisieten op de foto’s dienen alleen voor de styling.',
'Wasvoorschrift:','Machinewas koud op een fijnwasprogramma, binnenstebuiten keren, aan de lijn of in de droger op lage temperatuur drogen en niet bleken.',
'Maatbereik:','Kind 2 jaar tot en met Kind 9-10 jaar, Moeder S tot en met Moeder 2XL en Vader M tot en met Vader 3XL.',
'Maattabel - Shirt','Maat','Leeftijd','Gewicht (kg/lbs)','Lichaamslengte (cm)','Borst/buste (cm)','Mouw of rok (cm)','Broek/short of - (cm)','Heup (cm)','Taille (cm)','Kledinglengte (cm)',
'Red Heart Raglan is een eenvoudig, bijpassend familie-T-shirt dat speels oogt zonder al te gekleed te zijn. Dankzij de contrasterende rode mouwen en het kleine hartdetail valt de gezamenlijke look op in foto’s, terwijl het shirt gemakkelijk te combineren is met denim, shorts of casual rokken.',
'De bronselector bevat afzonderlijke bovenstukken, onderstukken en complete sets; dit concept bevat bewust alleen de bovenstukvarianten die door de maattabel worden ondersteund, omdat de productcategorie uitkomt op T-shirts en de aangeleverde maten het duidelijkst bij de bovenstukken aansluiten. De selectorwaarden voor onderstukken en sets blijven buiten de aanbieding totdat een afzonderlijk verzoek voor een onderstuk/set het exacte variantenmodel bevestigt.',
'Belangrijkste kenmerken:','Eén bijpassend T-shirt:','Dezelfde rood-witte look met korte mouwen in kinder-, moeder- en vadermaten.',
'Katoengevoel:','Op de detailpagina van de leverancier staat 95% katoen als samenstelling van de hoofdstof.',
'Maten voor het hele gezin:','Kindermaten van 90 tot en met 150, moedermaten van S tot en met 2XL en vadermaten van M tot en met 3XL.',
'Kleur die mooi uitkomt op foto’s:','Rode raglanmouwen, gestreepte banen op de mouwen en het hartdetail laten de bijpassende look opvallen.',
'Varianten op basis van de maattabel:','Elke maatoptie wordt ondersteund door een rij in de bijgevoegde maattabel van de leverancier.',
'Kies de kinder-, moeder- en vadermaten die je nodig hebt voor een ontspannen, bijpassende look met rode hartjes voor alledaagse familieherinneringen.'
]
TEXT[213,'pl']=[
'Materiał:','95% bawełny, zgodnie ze zweryfikowanymi informacjami o produkcie.',
'Rodzinny styl:','Sportowy, pasujący T-shirt dla mam, ojców, dziewczynek i chłopców, idealny na swobodne wyjścia, dni w parku, urodziny i rodzinne zdjęcia.',
'Wzór referencyjny:','Red Heart Raglan łączy biały korpus T-shirtu z kontrastowymi czerwonymi rękawami, paskami na rękawach i małym akcentem w kształcie serca.',
'Szczegóły fasonu:','Krótkie rękawy, okrągły dekolt, swobodny raglanowy fason T-shirtu i wspólna czerwono-biała kolorystyka dla dzieci, mam i ojców. Spódnice, szorty, buty, okulary przeciwsłoneczne i rekwizyty plenerowe na zdjęciach służą wyłącznie stylizacji.',
'Pielęgnacja:','Prać w pralce w zimnej wodzie na delikatnym programie, odwrócić na lewą stronę, suszyć rozwieszone lub w suszarce bębnowej w niskiej temperaturze i unikać wybielacza.',
'Zakres rozmiarów:','Dziecko 2 lata do Dziecko 9-10 lat, Mama S do Mama 2XL i Tata M do Tata 3XL.',
'Tabela rozmiarów - Koszulka','Rozmiar','Wiek','Masa ciała (kg/lbs)','Wzrost (cm)','Klatka piersiowa/biust (cm)','Rękaw lub spódnica (cm)','Spodnie/szorty lub - (cm)','Biodra (cm)','Talia (cm)','Długość odzieży (cm)',
'Red Heart Raglan to prosty, pasujący rodzinny T-shirt o radosnym, ale niezbyt odświętnym charakterze. Kontrastowe czerwone rękawy i mały detal w kształcie serca sprawiają, że wspólny styl jest dobrze widoczny na zdjęciach, a koszulka łatwo łączy się z dżinsem, szortami lub codziennymi spódnicami.',
'Źródłowy selektor zawiera oddzielne góry, doły i pełne komplety; ten szkic celowo uwzględnia tylko warianty góry potwierdzone tabelą, ponieważ przypisana kategoria produktu to T-shirty, a dostarczone wymiary najdokładniej opisują góry. Wartości selektora dotyczące dołów i kompletów pozostają poza ofertą do czasu, aż oddzielne zlecenie dotyczące dołu/kompletu potwierdzi dokładny model wariantów.',
'Najważniejsze cechy:','Jedna pasująca koszulka:','Ten sam czerwono-biały wygląd koszulki z krótkim rękawem w rozmiarach dla dziecka, mamy i taty.',
'Bawełniany chwyt:','Strona szczegółów dostawcy podaje 95% bawełny w składzie głównego materiału.',
'Zakres dla całej rodziny:','Rozmiary dziecięce od 90 do 150, dla mam od S do 2XL i dla ojców od M do 3XL.',
'Kolory gotowe do zdjęć:','Czerwone raglanowe rękawy, pasiaste pasy na rękawach i akcent w kształcie serca wyróżniają pasujący rodzinny styl.',
'Warianty potwierdzone tabelą:','Każda opcja rozmiaru ma potwierdzenie w wierszu załączonej tabeli dostawcy.',
'Wybierz potrzebne rozmiary dla dziecka, mamy i taty, aby stworzyć swobodny, pasujący strój z czerwonym sercem na codzienne rodzinne chwile.'
]
TEXT[213,'pt-BR']=[
'Tecido:','95% algodão, de acordo com os detalhes verificados do produto.',
'Estilo em família:','Uma camiseta esportiva combinando para mães, pais, meninas e meninos, prática para passeios casuais, dias no parque, aniversários e fotos em família.',
'Referência da estampa:','Red Heart Raglan combina o corpo branco da camiseta com mangas vermelhas contrastantes, listras nas mangas e um pequeno detalhe de coração.',
'Detalhes do modelo:','Mangas curtas, gola redonda, modelagem raglan descontraída e a mesma combinação de vermelho e branco para crianças, mães e pais. Saias, shorts, calçados, óculos de sol e objetos de cenário ao ar livre nas fotos servem apenas para compor o visual.',
'Cuidados:','Lave à máquina com água fria no ciclo delicado, vire do avesso, seque no varal ou na secadora em temperatura baixa e evite alvejante.',
'Grade de tamanhos:','Criança 2 anos a Criança 9-10 anos, Mãe S a Mãe 2XL e Pai M a Pai 3XL.',
'Tabela de medidas - Camiseta','Tamanho','Idade','Peso (kg/lbs)','Altura (cm)','Peito/busto (cm)','Manga ou saia (cm)','Calça/shorts ou - (cm)','Quadril (cm)','Cintura (cm)','Comprimento da peça (cm)',
'Red Heart Raglan é uma camiseta coordenada para a família, de visual simples e divertido sem ficar formal demais. As mangas vermelhas contrastantes e o pequeno coração destacam o visual combinado nas fotos, sem deixar de combinar facilmente com jeans, shorts ou saias casuais.',
'O seletor da fonte inclui peças de cima, peças de baixo e conjuntos completos separados; este rascunho lista intencionalmente apenas as variantes de peças de cima respaldadas pela tabela, pois a categoria do produto corresponde a camisetas e as medidas fornecidas dão suporte mais claro às peças de cima. Os valores do seletor para peças de baixo e conjuntos permanecem fora do anúncio até que uma solicitação separada de peça de baixo/conjunto confirme o modelo exato de variantes.',
'Principais características:','Uma camiseta coordenada:','O mesmo visual de camiseta de manga curta em vermelho e branco para tamanhos de criança, mãe e pai.',
'Toque de algodão:','A página de detalhes do fornecedor identifica 95% algodão na composição do tecido principal.',
'Grade para toda a família:','Tamanhos infantis de 90 a 150, de mãe de S a 2XL e de pai de M a 3XL.',
'Cores prontas para as fotos:','As mangas raglan vermelhas, as faixas listradas nas mangas e o detalhe de coração destacam o visual combinado.',
'Variantes respaldadas pela tabela:','Cada opção de tamanho corresponde a uma linha da tabela do fornecedor em anexo.',
'Escolha os tamanhos de criança, mãe e pai de que precisa para criar um visual fácil de combinar com coração vermelho para as lembranças do dia a dia em família.'
]
TEXT[214,'nl']=[
'Stof:','De exacte vezelsamenstelling was niet zichtbaar in het aangeleverde bewijsmateriaal.',
'Voor het gezin:','Een vrolijke look voor moeder en dochter, voor dagen in een resort, strandfoto’s, warme weekenden en ontspannen momenten in bijpassende kleding.',
'Printreferentie:','Red Resort combineert een felrood T-shirt met korte mouwen met een helderwitte plooirok.',
'Ontwerpdetails:','Complete set van een rood bovenstuk met korte mouwen en een witte plooirok; hoeden, tassen, zonnebrillen en schoenen dienen alleen voor de styling.',
'Wasvoorschrift:','Machinewas koud op een fijnwasprogramma, binnenstebuiten keren, aan de lijn drogen en zo nodig op lage temperatuur strijken.',
'Maatbereik:','Complete sets lopen van Kind 4 jaar tot en met Kind 9-10 jaar en Moeder S-2XL.',
'Maattabel - Tweedelige set','Maat','Leeftijd','Gewicht (kg/lbs)','Lichaamslengte (cm)','Borst/buste (cm)','Mouw of rok (cm)','Broek/short of - (cm)','Heup (cm)','Taille (cm)','Kledinglengte (cm)',
'Red Resort is een eenvoudige, vrolijke moeder-dochteroutfit rond een rood T-shirt en een witte plooirok. De look oogt verzorgd op foto’s en blijft casual genoeg voor zonnige wandelingen, dagen in het park en vakantieherinneringen.',
'Het bewijsmateriaal van de leverancier bevat een maattabel voor het bovenstuk, een maattabel voor de rok met numerieke rokmaten en een verkopersselector met de maten voor de complete set. De roktabel toont de rijen 110-150 waar die overeenkomen met de selector; rokmaten voor volwassenen blijven niet beschikbaar, omdat geen roktabel voor S-2XL is aangeleverd.',
'Belangrijkste kenmerken:','Complete outfit:','Elke maat bevat zowel het rode bovenstuk als de witte plooirok.',
'Styling voor moeder en dochter:','Elke keuze bevat één rood T-shirt en één witte plooirok voor één persoon.',
'Rijen op basis van de maattabel:','Elke variant wordt ondersteund door de verkopersselector; rokmaten verschijnen alleen waar de aangeleverde roktabel overeenkomt met de maat in de selector.',
'Kleuren die mooi uitkomen op foto’s:','Felrood en helderwit zijn eenvoudig te combineren voor strand- en resortoutfits.',
'Kies je maten:','Selecteer de maten voor moeder en kind afzonderlijk voor jullie bijpassende outfits.',
'Kies de setmaten die je nodig hebt voor een bijpassende rood-witte outfit op jullie volgende zonnige dag samen.'
]
TEXT[214,'pl']=[
'Materiał:','Dokładny skład włókien nie był widoczny w dostarczonych materiałach źródłowych.',
'Rodzinny styl:','Wyrazisty strój dla mamy i córki na dni w kurorcie, zdjęcia na plaży, ciepłe weekendy i swobodne chwile w pasujących ubraniach.',
'Wzór referencyjny:','Red Resort łączy intensywnie czerwony T-shirt z krótkim rękawem ze śnieżnobiałą plisowaną spódnicą.',
'Szczegóły fasonu:','Pełny komplet: czerwona góra z krótkim rękawem i biała plisowana spódnica; kapelusze, torby, okulary przeciwsłoneczne i buty to wyłącznie dodatki do stylizacji.',
'Pielęgnacja:','Prać w pralce w zimnej wodzie na delikatnym programie, odwrócić na lewą stronę, suszyć rozwieszone i w razie potrzeby prasować w niskiej temperaturze.',
'Zakres rozmiarów:','Pełne komplety są dostępne od Dziecko 4 lata do Dziecko 9-10 lat oraz Mama S-2XL.',
'Tabela rozmiarów - Komplet dwuczęściowy','Rozmiar','Wiek','Masa ciała (kg/lbs)','Wzrost (cm)','Klatka piersiowa/biust (cm)','Rękaw lub spódnica (cm)','Spodnie/szorty lub - (cm)','Biodra (cm)','Talia (cm)','Długość odzieży (cm)',
'Red Resort to prosty, radosny strój dla mamy i córki, którego podstawą są czerwony T-shirt i biała plisowana spódnica. Prezentuje się schludnie na zdjęciach, pozostając wystarczająco swobodnym na słoneczne spacery, dni w parku i wakacyjne wspomnienia.',
'Materiały dostawcy zawierają tabelę wymiarów góry, tabelę wymiarów spódnicy dla rozmiarów liczbowych oraz selektor sprzedawcy z rozmiarami pełnego kompletu. Wiersze tabeli spódnicy 110-150 są pokazane tam, gdzie pasują do selektora; wymiary spódnic dla dorosłych pozostają niedostępne, ponieważ nie dostarczono tabeli spódnic S-2XL.',
'Najważniejsze cechy:','Kompletny strój:','Każdy rozmiar obejmuje zarówno czerwoną górę, jak i białą plisowaną spódnicę.',
'Stylizacja mamy i córki:','Każdy wybór obejmuje jeden czerwony T-shirt i jedną białą plisowaną spódnicę dla jednej osoby.',
'Wiersze potwierdzone tabelą:','Każdy wariant jest potwierdzony selektorem sprzedawcy; wymiary spódnicy pojawiają się tylko tam, gdzie dostarczona tabela spódnicy odpowiada rozmiarowi w selektorze.',
'Paleta gotowa do zdjęć:','Intensywna czerwień i czysta biel łatwo komponują się w strojach na plażę i do kurortu.',
'Wybierz rozmiary:','Wybierz osobno rozmiary mamy i dziecka, aby stworzyć pasujące stroje.',
'Wybierz potrzebne rozmiary kompletów, aby stworzyć pasujący czerwono-biały strój na kolejny wspólny słoneczny dzień.'
]
TEXT[214,'pt-BR']=[
'Tecido:','A composição exata das fibras não estava visível nas evidências fornecidas.',
'Estilo em família:','Um visual vibrante para mãe e filha, feito para dias no resort, fotos na praia, fins de semana quentes e momentos descontraídos combinando.',
'Referência da estampa:','Red Resort combina uma camiseta vermelho-vivo de manga curta com uma saia plissada branca.',
'Detalhes do modelo:','Conjunto completo de blusa vermelha de manga curta e saia plissada branca; chapéus, bolsas, óculos de sol e calçados servem apenas para compor o visual.',
'Cuidados:','Lave à máquina com água fria no ciclo delicado, vire do avesso, seque no varal e, se necessário, passe em temperatura baixa.',
'Grade de tamanhos:','Os conjuntos completos vão de Criança 4 anos a Criança 9-10 anos e Mãe S-2XL.',
'Tabela de medidas - Conjunto de duas peças','Tamanho','Idade','Peso (kg/lbs)','Altura (cm)','Peito/busto (cm)','Manga ou saia (cm)','Calça/shorts ou - (cm)','Quadril (cm)','Cintura (cm)','Comprimento da peça (cm)',
'Red Resort é um conjunto simples e alegre para mãe e filha, composto por uma camiseta vermelha e uma saia plissada branca. O visual fica arrumado nas fotos e continua casual o suficiente para caminhadas ao sol, dias no parque e lembranças de férias.',
'As evidências do fornecedor trazem uma tabela de medidas da blusa, uma tabela da saia para tamanhos numéricos e um seletor do vendedor com os tamanhos do conjunto completo. As linhas 110-150 da tabela da saia são exibidas quando correspondem ao seletor; as medidas das saias adultas ficam indisponíveis porque não foi fornecida uma tabela de saia S-2XL.',
'Principais características:','Look completo:','Cada tamanho inclui a blusa vermelha e a saia plissada branca.',
'Estilo para mãe e filha:','Cada seleção inclui uma camiseta vermelha e uma saia plissada branca para uma pessoa.',
'Linhas respaldadas pela tabela:','Cada variante é respaldada pelo seletor do vendedor; as medidas da saia aparecem apenas quando a tabela fornecida corresponde ao tamanho do seletor.',
'Paleta pronta para as fotos:','Vermelho-vivo e branco são fáceis de coordenar em looks de praia e resort.',
'Escolha seus tamanhos:','Selecione os tamanhos de mãe e criança separadamente para seus looks combinando.',
'Escolha os tamanhos dos conjuntos de que precisa para montar um visual coordenado em vermelho e branco para o próximo dia ensolarado juntas.'
]
TEXT[215,'nl']=[
'Stof:','Lichte stof met een geweven uitstraling; de exacte vezelsamenstelling was niet zichtbaar in de aangeleverde tabel of afbeelding.',
'Voor het gezin:','Een zonnige look voor moeder en dochter, voor tuinwandelingen, vakanties, picknicks en gezinsfoto’s bij warm weer.',
'Printreferentie:','Golden Daisy combineert een mosterdgele mouwloze top met wit','madeliefjesborduurwerk en een ivoorkleurige broek met wijde pijpen en opengewerkte bloemen in dezelfde tint.',
'Ontwerpdetails:','Kies de top of broek afzonderlijk. De top heeft een los, mouwloos, uitlopend model; de broek heeft een instaptaille en soepel vallende wijde pijpen.',
'Wasvoorschrift:','Machinewas koud op een fijnwasprogramma, binnenstebuiten keren, aan de lijn drogen en niet bleken.',
'Maatbereik:','Top van Kind 2 jaar tot en met Kind 9-10 jaar en Moeder S-L; broek van Kind 1-2 jaar tot en met Kind 9-10 jaar en Moeder S-L.',
'Maattabel - Top en broek','Maat','Leeftijd','Gewicht (kg)','Lichaamslengte (cm)','Borst/buste top (cm)','Lengte top (cm)','Broeklengte (cm)','Heup top (cm)','Taille top (cm)','Broektaille (cm)',
'Golden Daisy is een vrolijke moeder-dochterlook opgebouwd uit twee bijpassende losse kledingstukken. De gele mouwloze top zorgt voor het stralende madeliefjesaccent, terwijl de ivoorkleurige broek een zachte textuur en een ontspannen silhouet met wijde pijpen toevoegt voor zomerfoto’s.',
'De bijgevoegde tabel vermeldt YC8970 als de top en YC8971 als de broek; daarom maakt dit concept via een keuze voor Type duidelijk welk kledingstuk de klant kiest. De maatgids sluit aan op dezelfde kinder- en moedermaten die klanten selecteren, met streepjes waar voor een kledingstuk in die maat geen tabelgegevens beschikbaar zijn.',
'Belangrijkste kenmerken:','Keuze voor afzonderlijke kledingstukken:','Met de Type-opties kiezen klanten de top of broek, in plaats van ervan uit te gaan dat het een gebundelde set is.',
'Maten voor moeder en dochter:','Alleen kinder- en moederrijen op basis van de tabel; er zijn geen vader- of jongensrijen verzonnen.',
'Kleuren die mooi uitkomen op foto’s:','Mosterdgeel en ivoor geven de bijpassende look een stralende, zachte uitstraling die gemakkelijk te stylen is.',
'Zomerse silhouetten:','Een mouwloze, uitlopende top en een broek met wijde pijpen houden de look luchtig.',
'Varianten op basis van de maattabel:','Elke Shopify-variant komt overeen met een zichtbare maatrij voor YC8970 of YC8971.',
'Kies de kledingstukken en maten die je nodig hebt voor een goudkleurige, bijpassende look op jullie volgende zonnige dag samen.'
]
TEXT[215,'pl']=[
'Materiał:','Lekki materiał o wyglądzie tkaniny; dokładny skład włókien nie był widoczny w dostarczonej tabeli ani na zdjęciu.',
'Rodzinny styl:','Słoneczny strój dla mamy i córki na spacery po ogrodzie, wakacje, pikniki i rodzinne zdjęcia w ciepłe dni.',
'Wzór referencyjny:','Golden Daisy łączy musztardowożółty top bez rękawów z białym','haftem w stokrotki oraz szerokie spodnie w kolorze kości słoniowej z ażurowym wzorem kwiatowym w tej samej tonacji.',
'Szczegóły fasonu:','Top i spodnie wybiera się oddzielnie. Top ma luźny, rozszerzający się ku dołowi fason bez rękawów; spodnie są wciągane i mają swobodnie układające się szerokie nogawki.',
'Pielęgnacja:','Prać w pralce w zimnej wodzie na delikatnym programie, odwrócić na lewą stronę, suszyć rozwieszone i unikać wybielacza.',
'Zakres rozmiarów:','Top od Dziecko 2 lata do Dziecko 9-10 lat i Mama S-L; spodnie od Dziecko 1-2 lata do Dziecko 9-10 lat i Mama S-L.',
'Tabela rozmiarów - Top i spodnie','Rozmiar','Wiek','Masa ciała (kg)','Wzrost (cm)','Klatka piersiowa/biust topu (cm)','Długość topu (cm)','Długość spodni (cm)','Biodra topu (cm)','Talia topu (cm)','Talia spodni (cm)',
'Golden Daisy to radosna propozycja dla mamy i córki złożona z dwóch pasujących, oddzielnych części garderoby. Żółty top bez rękawów wnosi wyrazisty motyw stokrotek, a spodnie w kolorze kości słoniowej dodają miękką fakturę i swobodny fason z szerokimi nogawkami do letnich zdjęć.',
'Załączona tabela określa YC8970 jako top, a YC8971 jako spodnie, dlatego w tym szkicu selektor dla kupującego jasno wskazuje wybór Typu. Przewodnik po rozmiarach odpowiada tym samym oznaczeniom dziecięcym i dla mam, które wybiera klient; kreski oznaczają brak danych dla danej części w tym rozmiarze.',
'Najważniejsze cechy:','Wybór oddzielnych części:','Opcje Typu pozwalają wybrać top lub spodnie, zamiast zakładać, że jest to komplet sprzedawany łącznie.',
'Rozmiary dla mamy i córki:','Tylko wiersze dziecięce i dla mam potwierdzone tabelą; nie dodano wymyślonych wierszy dla ojców ani chłopców.',
'Paleta gotowa do zdjęć:','Musztardowa żółć i kość słoniowa nadają pasującemu strojowi jasny, delikatny charakter i ułatwiają stylizację.',
'Letnie fasony:','Rozszerzający się top bez rękawów i spodnie z szerokimi nogawkami nadają stylizacji lekkość.',
'Warianty potwierdzone tabelą:','Każdy wariant Shopify odpowiada widocznemu wierszowi rozmiaru YC8970 lub YC8971.',
'Wybierz potrzebne części i rozmiary, aby stworzyć złocisty, pasujący strój na kolejny wspólny słoneczny dzień.'
]
TEXT[215,'pt-BR']=[
'Tecido:','Tecido leve com aparência de trama plana; a composição exata das fibras não estava visível na tabela ou imagem fornecida.',
'Estilo em família:','Um visual ensolarado para mãe e filha, feito para passeios no jardim, férias, piqueniques e fotos em família nos dias quentes.',
'Referência da estampa:','Golden Daisy combina uma blusa sem mangas amarelo-mostarda com bordado branco','de margaridas e uma calça de pernas amplas na cor marfim, com trabalho floral vazado no mesmo tom.',
'Detalhes do modelo:','Escolha a blusa ou a calça separadamente. A blusa tem modelagem solta, sem mangas e evasê; a calça tem cintura de vestir sem fecho e caimento amplo e descontraído nas pernas.',
'Cuidados:','Lave à máquina com água fria no ciclo delicado, vire do avesso, seque no varal e evite alvejante.',
'Grade de tamanhos:','Blusa de Criança 2 anos a Criança 9-10 anos e Mãe S-L; calça de Criança 1-2 anos a Criança 9-10 anos e Mãe S-L.',
'Tabela de medidas - Blusa e calça','Tamanho','Idade','Peso (kg)','Altura (cm)','Peito/busto da blusa (cm)','Comprimento da blusa (cm)','Comprimento da calça (cm)','Quadril da blusa (cm)','Cintura da blusa (cm)','Cintura da calça (cm)',
'Golden Daisy é uma proposta alegre para mãe e filha, formada por duas peças separadas e coordenadas. A blusa amarela sem mangas traz o destaque vibrante das margaridas, enquanto a calça marfim acrescenta textura suave e uma silhueta ampla e descontraída para as fotos de verão.',
'A tabela em anexo identifica YC8970 como a blusa e YC8971 como a calça, por isso este rascunho mantém a seleção clara para o comprador com uma opção de Tipo. O guia usa os mesmos nomes de tamanhos infantis e de mãe que o cliente seleciona, com traços quando uma peça não tem medidas publicadas naquele tamanho.',
'Principais características:','Seleção de peças separadas:','As opções de Tipo permitem escolher a blusa ou a calça, em vez de presumir um conjunto vendido junto.',
'Tamanhos para mãe e filha:','Somente linhas de criança e mãe respaldadas pela tabela; nenhuma linha de pai ou menino foi inventada.',
'Paleta pronta para as fotos:','Amarelo-mostarda e marfim deixam o visual coordenado vibrante, suave e fácil de combinar.',
'Silhuetas de verão:','A blusa sem mangas em evasê e a calça de pernas amplas mantêm o visual leve.',
'Variantes respaldadas pela tabela:','Cada variante Shopify corresponde a uma linha de tamanho visível de YC8970 ou YC8971.',
'Escolha as peças e os tamanhos de que precisa para montar um visual dourado combinando para o próximo dia ensolarado juntas.'
]
