query FaqTranslationsInventory($marketId:ID) { translatableResource(resourceId:"gid://shopify/Page/161933381") { resourceId translatableContent(marketId:$marketId) { key locale value digest type } t_ar: translations(locale:"ar",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_cs: translations(locale:"cs",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_da: translations(locale:"da",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_de: translations(locale:"de",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_el: translations(locale:"el",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_en: translations(locale:"en",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_es: translations(locale:"es",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_fi: translations(locale:"fi",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_fr: translations(locale:"fr",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_he: translations(locale:"he",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_hi: translations(locale:"hi",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_it: translations(locale:"it",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_ja: translations(locale:"ja",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_ko: translations(locale:"ko",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_nl: translations(locale:"nl",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_no: translations(locale:"no",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_pl: translations(locale:"pl",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_pt_BR: translations(locale:"pt-BR",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_ro: translations(locale:"ro",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_ru: translations(locale:"ru",marketId:$marketId) { key locale value outdated updatedAt market { id } }
t_sv: translations(locale:"sv",marketId:$marketId) { key locale value outdated updatedAt market { id } } } }
