from pathlib import Path
import json,hashlib,datetime
B=Path('dresslikemommy-growth-2026/02_AUDIT_PACKETS/2026-09-09-microsoft-ads-rebuild/heartbeat-20260911-2237')
M=json.loads((B/'canonical_before_manifest.json').read_text())
sha=lambda x:hashlib.sha256(x).hexdigest()
files={p:Path(p).read_text() for p in M['files_sha256']}
assert all(sha(Path(p).read_bytes())==h for p,h in M['files_sha256'].items()),'CANONICAL_DRIFT_STOP'
A='2026-09-12-microsoft-paused-search-build-and-language-repair'
E='2026-09-09-microsoft-ads-rebuild/heartbeat-20260911-2237/READBACK.md'
ops=[]
def replace(p,old,new):
 assert files[p].count(old)==1,(p,'AMBIGUOUS_REPLACEMENT')
 files[p]=files[p].replace(old,new,1);ops.append({'path':p,'old':old,'new':new})
def append(p,new):
 old=files[p][-min(120,len(files[p])):]
 replace(p,old,old+'\n\n'+new.rstrip()+'\n')
block=f'''## September12 Microsoft paused U.S. and German build verified

TA-15; anchor {A}. Account477439/customer770182 is LIVE_VERIFIED in the task-owned background IAB. Three separate native imports created exactly two Paused Search campaigns, two Paused groups/six Paused Exact keywords, then two Paused RSAs/fourteen campaign Phrase negatives. All three receivers report zero existing-item syncs and deletions; the two child imports explicitly report zero errors. No creation import may be repeated. US506254907/group1272136755587035/ad79508657389070 and DE506254908/group1262241151661314/ad78890182372245 are verified saved objects. The original eleven campaign identities, pause states, types, budgets and bid strategies remain intact; thirteen campaigns are now Paused.

US English/United States and DE German/Germany retain presence-only targeting at zero modifiers, configured5/3USD daily budgets and Maximize Clicks with maximum CPC checked at0.15USD. These are paused settings, not spend authority or achieved CPC. AI Max, text customization, final URL expansion and search term matching are off. Both groups show Auto bids, effective MaxClicks and Microsoft sites and select traffic. That network choice does not prove Audience exclusion. Microsoft initially defaulted the DE group to English despite its German campaign; one independently reviewed language-only Save corrected it and reopening verified German. Two earlier country Saves are separately verified. No parent settings Save followed the child imports.

Both ad editors reopen with exact eight headlines/three descriptions, paths, English/German HTTPS dresses destinations and literal campaign-specific UTM suffixes. All fourteen negative IDs/texts/Phrase campaign scopes are verified, seven per parent. Both editors show eleven Pin controls without numbered positions; per-asset selected pin metadata was not exposed. Native editorial approval and actual URL-parameter transport remain unverified. The combined mapper displayed only its first ten rows; this limitation was independently accepted before the contained import and all sixteen resulting items were subsequently enumerated.

The September11 five-Save/six-field purchase-goal and automatic-ad-control repairs remain completed dated evidence: one primary purchase event goal counts All with variable USD0 fallback, legacy checkout goals secondary and two automatic ad-creation opt-ins off. UET36005151 Active and MSCLKID On are prior verified settings, not a fresh purchase test. Prior six-month-limited94 events/last event four days ago and seven-day regional pageview27%/view_item0% remain dated evidence; purchase Healthy had no regional sample. Real purchase/value/currency/order deduplication, supported publisher-cookie correction, EEA/UK/CH consent and actual contribution remain open. No fake order, consent declaration, unsupported source edit or repeated app error probe occurred.

The existing every-four-hour Microsoft heartbeat delivered the September11 22:37 continuation; this September12 recovery finished the interrupted build without duplicate objects or another schedule. Current next internal action: use the supported app/receiver path to verify regional consent and a genuine purchase before any paid experiment. Actual costs and exact numeric cash/loss/launch authority remain required. Parent One Owner Action stays owner Shopify Admin publication of existing verified theme137888792673; peer claims, all nine full-paid controls and full-paidNONE are preserved. Evidence:{E}. Overall operational outcome remains PARTIAL; no sales, CPA, ROAS or profit improvement is claimed.
'''
for p in ['ops/marketing/current_marketing_state.md','ops/marketing/operator_cockpit.md']:
 s=files[p];i=s.index('## September11 Microsoft purchase goals and ad controls');j=s.index('\n## ',i+4);replace(p,s[i:j],block.rstrip()+'\n')
p='ops/AGENT_COORDINATION.md';old=next(l for l in files[p].splitlines() if l.startswith('| Current owner Microsoft Ads tracking and campaign rebuild |'))
replace(p,old,f'| Current owner Microsoft Ads tracking and campaign rebuild | Microsoft477439/customer770182; UET36005151/APP931561569; US506254907/DE506254908 and exact saved children | `PAUSED_US_DE_BUILD_VERIFIED__PURCHASE_CONSENT_LAUNCH_GATED` | root01a08703 sole Microsoft writer and own canonical integrator; international_campaign_build source preparation; paused_import_verifier independent exact reviews; UX owns theme | Current owner ongoing nonspend tracking repair and qualified paused USEN/DEDE preparation; existing every4h heartbeat delivered; current own shared checkpoint lease from parent | No paid activation, numeric spend allocation, billing/security/account switch, fake purchase, consent workaround or theme publication; preserve peers and frozen inputs | {E}; import-review/; anchor{A} | Three imports created2campaigns/2groups/6Exactkeywords/2RSAs/14Phrasenegatives; zero syncs/deletes; both child imports zero errors. Two country Saves and one DE group language repair reopened verified. All13Paused; original11 settings preserved. USEN/DEDE presence-only, MaxClicks0.15cap, configured5/3USD, four expansionsOff, selecttraffic network. Purchase/consent/source/economics/editorial/paidlaunch open. No reimport; parent theme action and fullpaidNONE preserved. Own checkpoint lease releases after validation |')
p='ops/marketing/action_queue.md';old=next(l for l in files[p].splitlines() if l.startswith('| P0 | YELLOW | `TA-15`'))
replace(p,old,f'| P0 | YELLOW | `TA-15` Finish Microsoft477439/770182 purchase and regional consent acceptance | root01a08703 sole Microsoft writer; paused_import_verifier independent reviews; UX owns theme | Paused USEN/DEDE campaigns and complete initial children saved; real purchase, supported source/consent, actual economics and numeric paid launch open | current_marketing_state.md; {E}; anchor{A} | Paid traffic | In progress | Technical dependency | 2campaigns/2groups/6Exactkeywords/2RSAs/14campaignPhrase negatives verified; country/presence/0.15cap saved; DE group language corrected; all13Paused and original11 settings preserved; existing4h heartbeat delivered | Verify supported app consent and genuine purchase/value/currency/dedup receiver; retain exact objects and do not repeat imports or goal repair. No enablement or numeric launch authority | 2026-09-12 | Finish purchase/consent acceptance before any measured paid experiment |')
p='ops/marketing/blocker_board.md';old=next(l for l in files[p].splitlines() if l.startswith('TA-15: Microsoft477439/customer770182 authenticated;'))
short=f'TA-15: Native paused preparation is VERIFIED: US506254907/DE506254908, two groups, six Exact keywords, two RSAs and fourteen campaign Phrase negatives, with zero import syncs/deletions and zero errors in both child imports. Correct language, country/presence, MaxClicks0.15cap and configured5/3USD settings saved; DE group English default was corrected to German once. All13campaignsPaused/original11 settings preserved. This clears explicit paused persistence and native cap/inheritance qualification, not actual CPC, editorial approval, regional consent, true purchase/value/currency/dedup or profit. Supported publisher-cookie/app correction, actual costs and exact launch cash/loss remain open. Earlier goal repairs and failed app paths stay dated evidence. Existing4h heartbeat delivered; no repeat imports. Parent theme owner-publication action, fullpaidNONE and peers unchanged. Evidence:{E}; anchor{A}.'
replace(p,old,short)
p='ops/PROBLEM_TRACKER.md';s=files[p];i=s.index('### Microsoft September11 purchase receiver and paused preparation checkpoint');j=s.index('### `PROB-2026-09-06-MICROSOFT-PURCHASE-TRUTH`',i)
replace(p,s[i:j],'### Microsoft September12 purchase acceptance and saved paused build checkpoint\n\n'+short+'\n\nAttempt and falsifier: native group creation defaulted the German group to English. Stop-before-ad review bound one explicit German correction to group1262241151661314; Save/reopen passed and subsequent ads were added only after corrected postflight. An own unchanged US parent inspection form displayed an exit warning; root selected No, obtained independent scope review, then discarded that form without Save and verified the normal saved group page. DE intermediate exit dialog was not observed; no dialog-free claim. Six-row combined-preview limit and stronger pin-metadata limitation are preserved in receipts. No source reinstall or duplicate sender.\n\n')
needle='### `PROB-2026-09-06-MICROSOFT-PURCHASE-TRUTH`\n\n';replace(p,needle,needle+f'- September12: {short}\n\n')
append('ops/marketing/daily_scorecard.md',f'''## September12 Microsoft native preparation result

{A}: IMPLEMENTED and VERIFIED two Paused Search campaigns, two Paused groups, six Paused Exact keywords, two Paused RSAs and fourteen campaign Phrase negatives. Three native imports report zero existing syncs/deletions; both child imports explicitly report zero errors. Two country-target Saves and one DE language-only correction separately reopened verified. Final thirteen campaigns Paused; original eleven identity/type/budget/bid states preserved. New configured US5/DE3USD and MaxClicks0.15maximum remain configuration only. No new Shopify or GA4 order query was run, and no revenue, CPA, ROAS or retained-profit improvement is established. Native editorial review, genuine purchase/consent/source repair and actual economics remain open. Preserve every earlier cohort and its dates. Evidence:{E}.''')
append('ops/marketing/decision_log.md',f'''## September12 Microsoft native preparation outcomes

DLM-DEC-2026-09-11-MICROSOFT-PAUSED-SHELL-IMPORT and DLM-DEC-2026-09-11-MICROSOFT-COUNTRY-PRESENCE-TARGETING retain their frozen contracts and predictions: two empty paused shells with native0.15cap and exact country/presence, zero existing updates. Observed: campaigns506254907/506254908 created once, English/German, configured5/3USD, MaxClicks0.15cap, four expansionsOff; one country Save each, reopened presence-only/zero modifiers. Shell postflight26checks plus66original fields and country postflight25checks pass.

DLM-DEC-2026-09-12-MICROSOFT-PAUSED-DRESS-CHILDREN: exact new scope2groups/6keywords with OwnedAndOperatedOnly distribution and no existing updates. Observed receiver met counts/zeroerrors, but German-language inheritance was falsified by saved English. DLM-DEC-2026-09-12-MICROSOFT-DE-GROUP-LANGUAGE fixed that one group explicitly German after15check independent review; reopened German and18check corrected postflight passed. No duplicate import. Network choice is Microsoft sites and select traffic, not proof of Audience exclusion.

DLM-DEC-2026-09-12-MICROSOFT-PAUSED-ADS-NEGATIVES froze sixteen source rows and9-of77 permitted preferences. Critical uncertainty was native first-ten-row preview and unproved row-enum acceptance. Independent22check preflight accepted containment after earlier complete RSA preview; one actual Import yielded2ads/14campaign negatives and allothernew/synced/deleted/errors0. All16saved identities and contents were enumerated; exact literal URLs/suffixes preserved. Campaign/group/keyword pause and original11 settings persisted. Stronger selected pin metadata, editorial approval, actual CPC, attribution/consent and profit remain open. No paid authority or scale recommendation follows. Evidence:{E}; anchor{A}.''')
append('ops/marketing/review_log.md',f'''## September12 Microsoft paused native build review

/root/paused_import_verifier, DID_NOT_BUILD_OR_EXECUTE, reviewed root's saved native evidence and frozen source files. Shell pre22/post26checks plus66originalcampaign fields; country pre19/post25; group/keyword finalpre30 with80native cells, DElanguage pre15 and correctedpost18; combined finalpre22 with290visible native cells and explicit six-row preview limit. Actual combined receiver is2Ads/14Campaignnegativekeywords with all other creations/syncs/deletes/errors0; both ad editors and fourteen negative rows read back exactly. Final preservation records all13campaign IDs/status/types/budgets/strategies and bothnewgroup/sixkeyword pause states. Final combined postflight32checks,30populated ad-asset comparisons and78campaign-field comparisons PASS_WITH_LIMITS. Reviewer did not independently replay the browser. Both editors expose8headlines/3descriptions and11Pin buttons, but no stronger perassetselectedpinmetadata proof. No native editorial, real purchase, regionalconsent, actualCPC or profit certification. Final bound reviews live in heartbeat-20260911-2237/import-review/; evidence:{E}; anchor{A}.''')
p='ops/marketing/memory_digest.md';replace(p,'# Marketing Memory Digest\n','# Marketing Memory Digest\n\n## September12 Microsoft saved paused objects; measurement remains open\n\n'+short+'\n\nReuse exact saved group IDs1272136755587035/1262241151661314 and ad IDs79508657389070/78890182372245. Do not repeat any of the three creation imports. Native German parent language did not guarantee German group language; the single reviewed correction is already saved. The current task tab is task-owned IAB7/browser1, subject to fresh availability check; do not reuse oldmissingtab3 or personalChrome. Continue through ops/prompts/paid-growth-ai-army-continuation-prompt.md.\n')
append('ops/AGENT_WORKLOG.md',f'''## 2026-09-12 — Microsoft paused U.S./German build and language repair verified

AGENT_CONTINUITY_ANCHOR: {A}
task_entities: TA-15,477439,770182,36005151,931561569,506254907,506254908,1272136755587035,1262241151661314,79508657389070,78890182372245,PROB-2026-09-06-MICROSOFT-PURCHASE-TRUTH
task_stage: HANDOFF
next_action_id: READ_ONLY_MARKETING_RECONCILIATION

The September11 22:37 scheduled Microsoft continuation and September12 recovery completed the exact nonspend paused build. Three separate native imports created2campaigns, then2groups/6keywords, then2RSAs/14campaignnegatives, with zero existing syncs/deletions across all three and explicit zero errors in both child imports. Two country-only Saves installed US/Germany presence-only and zero modifiers. German group creation unexpectedly selected English; independent15check review authorized one explicit German Save, then a settings reopen and18check corrected postflight verified it before adding ads. Exact object IDs and all native receipts are in {E}. No creation rows may be resubmitted after interruption.

Final readback: all13 campaigns Paused; original11 IDs/names/types/budgets/strategies preserved. New English/German parents retain configured5/3USD, MaximizeClicks maximum0.15USD and four expansion controlsOff. Both groupsPaused/AutoMaxClicks/Microsoftsitesandselecttraffic; all6keyword IDs/texts/Paused/Exact/auto preserved. Ads79508657389070 and78890182372245 are Paused, with exact8headlines/3descriptions/paths/HTTPS destinations/UTM suffixes. Fourteen unique Campaign Phrase negative IDs and texts are verified,7perparent. Native editorial approval and actual CPC are not yet proven. Pin controls show no numbered assignments; stronger perassetselectedmetadata not exposed. First10of16 preview limitation was accepted before finalImport; all16savedrows subsequently enumerated. No Audience-only/exclusion or fullplatformperfection claim.

Own US parent inspection Cancel showed unexpected unsaved form warning; No preserved it, independent scope review qualified discarding the unchanged own form, then Yes returned normal savedgroups without Save. DE intermediate exit dialog was not captured; no dialog-free claim. No new app-load/Shopify order probing, purchase staging, consent pledge, source patch, activation, billing, security or peer production change. Existing4h heartbeat continues; no new automation or goal. Prior purchase-goal/automatic-ad-control repairs and regional-signal limitations remain historical evidence, not a new true purchase acceptance. Actual costs/cash/loss authority and retained profit remain unknown.

Canonical integration uses the parent's explicit narrow lease, exact before hashes and reversible replacements of only this Microsoft/TA-15 checkpoint. All nine full-paid control fields, parent One Owner Action to publish existing verified theme137888792673 in Shopify Admin and every unrelated peer byte are preserved. Validation receipts and independent preservation review will accompany the completed checkpoint. The context compiler returned AMBIGUOUS_RELEVANT_ANCHOR on the broad continuation; root used exact owning TA-15/claim/anchor rather than rewriting the compiler.

source_live_evidence_as_of: 2026-09-12
live_state_mode: STALE_READBACK_REQUIRED
effective_approval_policy: FRESH_ACTION_TIME_APPROVAL_REQUIRED
approved_external_scope: NONE
exact_microsoft_surface_state: LIVE_VERIFIED
current_exact_nonspend_scope: Existing user-authorized tracking repair and qualified Paused USEN/DEDE preparation; completed objects preserved, no paid enablement.
decision_depends_on_uncertain_state: true
decision_changing_evidence: Genuine purchase value/currency/order-dedup and EEA/UK/CH consent acceptance, supported app correction, actual contribution/cash/loss and exact numeric paid launch scope.
if_evidence_supports_recommendation: Prepare and independently review the smallest exact measured paid experiment within current explicit numeric authority; do not infer authority from this build.
if_evidence_opposes_recommendation: Keep saved campaignsPaused, repair the supported measured defect and continue independent owner-approved sales work; no blind reimport or bid escalation.
material_decision: true
independent_verifier: /root/paused_import_verifier
verifier_independence: DID_NOT_BUILD_OR_EXECUTE

Next internal Microsoft action: verify supported app consent and genuine purchase receiver before a measured paid launch. Overall requested profitable operation remains PARTIAL. Continue with ops/prompts/paid-growth-ai-army-continuation-prompt.md and this exact anchor; preserve the parent owner-publication action and all peer ownership.
''')
plan={'created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'anchor':A,'scope':'Only root01a08703 Microsoft/TA-15 current checkpoint; no authoritative-control, peer, global owner-action, source CSV or instruction changes','before_manifest_sha256':sha((B/'canonical_before_manifest.json').read_bytes()),'operations':ops,'file_count':len(set(o['path'] for o in ops)),'operation_count':len(ops),'expected_after_sha256':{p:sha(s.encode()) for p,s in files.items()},'applied':False}
(B/'canonical_checkpoint_plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
print('Prepared',len(ops),'exact replacements across',plan['file_count'],'files; no canonical writes.')
print('PLAN_SHA256',sha((B/'canonical_checkpoint_plan.json').read_bytes()))
