query MeowSource { shop { name primaryDomain { host } } product(id:"gid://shopify/Product/7533458194529") { id title handle status publishedAt onlineStoreUrl descriptionHtml seo { title description } variants(first:30) { nodes { id title price selectedOptions { name value } } pageInfo { hasNextPage endCursor } } images(first:20) { nodes { id url altText } pageInfo { hasNextPage endCursor } } } translatableResource(resourceId:"gid://shopify/Product/7533458194529") { resourceId translatableContent { key value digest locale } } }
