query FaqSizingGuideSource { article(id:"gid://shopify/Article/559700574305") { id handle title body isPublished updatedAt } translatableResource(resourceId:"gid://shopify/Article/559700574305") { resourceId translatableContent { key locale value digest type } t_ar: translations(locale:"ar") { key locale value outdated updatedAt market { id } }
t_cs: translations(locale:"cs") { key locale value outdated updatedAt market { id } }
t_da: translations(locale:"da") { key locale value outdated updatedAt market { id } }
t_de: translations(locale:"de") { key locale value outdated updatedAt market { id } }
t_el: translations(locale:"el") { key locale value outdated updatedAt market { id } }
t_es: translations(locale:"es") { key locale value outdated updatedAt market { id } }
t_fi: translations(locale:"fi") { key locale value outdated updatedAt market { id } }
t_fr: translations(locale:"fr") { key locale value outdated updatedAt market { id } }
t_he: translations(locale:"he") { key locale value outdated updatedAt market { id } }
t_hi: translations(locale:"hi") { key locale value outdated updatedAt market { id } }
t_it: translations(locale:"it") { key locale value outdated updatedAt market { id } }
t_ja: translations(locale:"ja") { key locale value outdated updatedAt market { id } }
t_ko: translations(locale:"ko") { key locale value outdated updatedAt market { id } }
t_nl: translations(locale:"nl") { key locale value outdated updatedAt market { id } }
t_no: translations(locale:"no") { key locale value outdated updatedAt market { id } }
t_pt_BR: translations(locale:"pt-BR") { key locale value outdated updatedAt market { id } }
t_ro: translations(locale:"ro") { key locale value outdated updatedAt market { id } } } }
