"""Builds collection_translations.json for the two new occasion collections (20 published locales)."""
import json, pathlib
D = {
"ar":"مواعيد التوصيل تقديرية؛ اطّلع على تاريخ الوصول المتوقع في صفحة كل منتج.",
"cs":"Doby doručení jsou odhadované; odhadované datum doručení najdete na stránce každého produktu.",
"da":"Leveringstider er estimater; se den forventede leveringsdato på hver produktside.",
"de":"Lieferzeiten sind Schätzungen; das voraussichtliche Lieferdatum finden Sie auf jeder Produktseite.",
"el":"Οι χρόνοι παράδοσης είναι εκτιμήσεις· δείτε την εκτιμώμενη ημερομηνία άφιξης στη σελίδα κάθε προϊόντος.",
"es":"Los plazos de entrega son estimaciones; consulta la fecha estimada de llegada en la página de cada producto.",
"fi":"Toimitusajat ovat arvioita; katso arvioitu saapumispäivä kunkin tuotteen sivulta.",
"fr":"Les délais de livraison sont des estimations ; consultez la date d'arrivée estimée sur chaque page produit.",
"he":"זמני המשלוח הם הערכה; את תאריך ההגעה המשוער אפשר לראות בעמוד של כל מוצר.",
"hi":"डिलीवरी का समय अनुमानित है; हर प्रोडक्ट पेज पर अनुमानित पहुँचने की तारीख देखें।",
"it":"I tempi di consegna sono stime; consulta la data di arrivo stimata nella pagina di ogni prodotto.",
"ja":"お届け日数は目安です。各商品ページでお届け予定日をご確認ください。",
"ko":"배송 기간은 예상치이며, 각 상품 페이지에서 예상 도착일을 확인하세요.",
"nl":"Levertijden zijn schattingen; bekijk de geschatte aankomstdatum op elke productpagina.",
"no":"Leveringstider er estimater; se forventet leveringsdato på hver produktside.",
"pl":"Czas dostawy jest szacunkowy; szacowaną datę dostawy sprawdzisz na stronie każdego produktu.",
"pt-BR":"Os prazos de entrega são estimativas; confira a data estimada de chegada na página de cada produto.",
"ro":"Termenele de livrare sunt estimative; vezi data estimată de sosire pe pagina fiecărui produs.",
"ru":"Сроки доставки ориентировочные; ориентировочную дату доставки смотрите на странице каждого товара.",
"sv":"Leveranstiderna är uppskattningar; se det beräknade leveransdatumet på varje produktsida.",
}
B = " Dress Like Mommy"
# locale: (title, body sentence(s), meta_title, meta_description)
XMAS = {
"ar":("ملابس عيد الميلاد المتطابقة للعائلة","كنزات وبيجامات عيد الميلاد المتطابقة للعائلة بأكملها، مصممة لصور بطاقات عيد الميلاد وليالي تزيين الشجرة وصباح العيد. تصاميم محبوكة بالرنة وسانتا وندف الثلج والنقوش الإسكندنافية بمقاسات للكبار والأطفال.","ملابس وكنزات عيد الميلاد المتطابقة للعائلة |"+B,"كنزات وبيجامات عيد الميلاد المتطابقة للعائلة لصور بطاقات الأعياد وصباح العيد. تصاميم محبوكة بالرنة وسانتا والنقوش الإسكندنافية بمقاسات للكبار والأطفال."),
"cs":("Sladěné vánoční oblečení pro celou rodinu","Sladěné vánoční svetry a pyžama pro celou rodinu, jako stvořené pro fotky na vánoční přání, zdobení stromečku i vánoční ráno. Pletené vzory se soby, Santou, vločkami a severskými motivy ve velikostech pro dospělé i děti.","Sladěné vánoční oblečení a svetry pro rodinu |"+B,"Sladěné rodinné vánoční svetry a pyžama pro fotky na vánoční přání i vánoční ráno. Pletené vzory se soby, Santou a severskými motivy pro dospělé i děti."),
"da":("Matchende juletøj til familien","Matchende julesweatre og julepyjamas til hele familien, skabt til julekortsbilleder, aftener med juletræspynt og julemorgen. Strik med rensdyr, julemand, snefnug og nordiske mønstre i størrelser til voksne og børn.","Matchende juletøj og julesweatre til familien |"+B,"Matchende julesweatre og julepyjamas til familien – til julekortsbilleder og julemorgen. Strik med rensdyr, julemand og nordiske mønstre til voksne og børn."),
"de":("Passende Weihnachtsoutfits für die Familie","Passende Weihnachtspullover und Schlafanzüge für die ganze Familie, gemacht für Weihnachtskartenfotos, gemütliche Abende beim Baumschmücken und den Weihnachtsmorgen. Strickmuster mit Rentieren, Weihnachtsmann, Schneeflocken und nordischen Motiven in Größen für Erwachsene und Kinder.","Passende Weihnachtsoutfits & Pullover für die Familie |"+B,"Passende Weihnachtspullover und Schlafanzüge für die Familie – für Weihnachtskartenfotos und den Weihnachtsmorgen. Rentier-, Weihnachtsmann- und Norwegermuster für Groß und Klein."),
"el":("Ασορτί χριστουγεννιάτικα σύνολα για την οικογένεια","Ασορτί χριστουγεννιάτικα πουλόβερ και πιτζάμες για όλη την οικογένεια, για φωτογραφίες χριστουγεννιάτικων καρτών, βραδιές στολισμού του δέντρου και το πρωί των Χριστουγέννων. Πλεκτά με ταράνδους, Άγιο Βασίλη, χιονονιφάδες και σκανδιναβικά μοτίβα σε μεγέθη για ενήλικες και παιδιά.","Ασορτί χριστουγεννιάτικα σύνολα & πουλόβερ για την οικογένεια |"+B,"Ασορτί οικογενειακά χριστουγεννιάτικα πουλόβερ και πιτζάμες για φωτογραφίες καρτών και το πρωί των Χριστουγέννων. Πλεκτά με ταράνδους και Άγιο Βασίλη για μικρούς και μεγάλους."),
"es":("Conjuntos navideños a juego para la familia","Suéteres y pijamas navideños a juego para toda la familia, pensados para las fotos de la postal navideña, las noches de decorar el árbol y la mañana de Navidad. Tejidos con renos, Papá Noel, copos de nieve y motivos nórdicos en tallas para adultos y niños.","Conjuntos y suéteres navideños a juego para la familia |"+B,"Suéteres y pijamas navideños a juego para la familia, para la foto de la postal y la mañana de Navidad. Tejidos con renos, Papá Noel y motivos nórdicos para adultos y niños."),
"fi":("Perheen yhteensopivat jouluasut","Yhteensopivat jouluneuleet ja -pyjamat koko perheelle joulukorttikuviin, kuusenkoristeluiltoihin ja jouluaamuun. Neuleita poro-, joulupukki-, lumihiutale- ja pohjoismaisilla kuvioilla aikuisten ja lasten koissa.","Perheen yhteensopivat jouluasut ja -neuleet |"+B,"Yhteensopivat jouluneuleet ja -pyjamat koko perheelle joulukorttikuviin ja jouluaamuun. Poro-, joulupukki- ja pohjoismaisia neuleita aikuisille ja lapsille."),
"fr":("Tenues de Noël assorties pour la famille","Des pulls et pyjamas de Noël assortis pour toute la famille, parfaits pour les photos de carte de Noël, les soirées de décoration du sapin et le matin de Noël. Tricots à motifs rennes, Père Noël, flocons et nordiques, en tailles adultes et enfants.","Tenues et pulls de Noël assortis pour la famille |"+B,"Pulls et pyjamas de Noël assortis pour la famille, pour la photo de la carte de Noël et le matin de Noël. Tricots rennes, Père Noël et nordiques, adultes et enfants."),
"he":("תלבושות חג המולד תואמות למשפחה","סוודרים ופיג'מות תואמים לחג המולד לכל המשפחה, מושלמים לצילומי כרטיסי ברכה, לערבי קישוט העץ ולבוקר חג המולד. סריגים עם איילים, סנטה, פתיתי שלג ודוגמאות נורדיות במידות למבוגרים ולילדים.","תלבושות וסוודרים תואמים לחג המולד למשפחה |"+B,"סוודרים ופיג'מות תואמים לחג המולד לכל המשפחה, לצילומי כרטיסי ברכה ולבוקר החג. סריגים עם איילים, סנטה ודוגמאות נורדיות למבוגרים ולילדים."),
"hi":("परिवार के लिए मैचिंग क्रिसमस आउटफ़िट","पूरे परिवार के लिए मैचिंग क्रिसमस स्वेटर और पजामे, क्रिसमस कार्ड की फ़ोटो, क्रिसमस ट्री सजाने वाली शामों और क्रिसमस की सुबह के लिए बने। रेनडियर, सांता, स्नोफ़्लेक और नॉर्डिक डिज़ाइन वाले निटवियर, बड़ों और बच्चों के साइज़ में।","परिवार के लिए मैचिंग क्रिसमस आउटफ़िट और स्वेटर |"+B,"परिवार के लिए मैचिंग क्रिसमस स्वेटर और पजामे, हॉलिडे कार्ड की फ़ोटो और क्रिसमस की सुबह के लिए। रेनडियर, सांता और नॉर्डिक निटवियर बड़ों और बच्चों के साइज़ में।"),
"it":("Outfit natalizi coordinati per la famiglia","Maglioni e pigiami natalizi coordinati per tutta la famiglia, pensati per le foto dei biglietti di Natale, le serate a decorare l'albero e la mattina di Natale. Maglie con renne, Babbo Natale, fiocchi di neve e motivi nordici in taglie per adulti e bambini.","Outfit e maglioni natalizi coordinati per la famiglia |"+B,"Maglioni e pigiami natalizi coordinati per la famiglia, per le foto degli auguri e la mattina di Natale. Renne, Babbo Natale e motivi nordici per adulti e bambini."),
"ja":("家族おそろいのクリスマスコーデ","クリスマスカードの写真撮影や、ツリーを飾る夜、クリスマスの朝にぴったりな、家族みんなでおそろいのクリスマスセーターとパジャマ。トナカイ、サンタ、雪の結晶、ノルディック柄のニットを大人用とキッズ用のサイズでご用意しています。","家族おそろいのクリスマスコーデ＆セーター |"+B,"クリスマスカードの写真やクリスマスの朝にぴったりな、家族おそろいのクリスマスセーターとパジャマ。トナカイ、サンタ、ノルディック柄のニットを大人・キッズサイズで。"),
"ko":("가족 크리스마스 패밀리룩","크리스마스 카드 사진, 트리 꾸미는 저녁, 크리스마스 아침을 위해 온 가족이 맞춰 입는 크리스마스 스웨터와 잠옷. 순록, 산타, 눈송이, 노르딕 패턴 니트를 성인과 아동 사이즈로 만나보세요.","가족 크리스마스 패밀리룩 & 스웨터 |"+B,"크리스마스 카드 사진과 크리스마스 아침을 위해 온 가족이 맞춰 입는 크리스마스 스웨터와 잠옷. 순록, 산타, 노르딕 니트를 성인과 아동 사이즈로 만나보세요."),
"nl":("Bijpassende kerstoutfits voor het gezin","Bijpassende kersttruien en -pyjama's voor het hele gezin, gemaakt voor kerstkaartfoto's, avonden met de kerstboom optuigen en kerstochtend. Breisels met rendieren, de kerstman, sneeuwvlokken en Noorse motieven in maten voor volwassenen en kinderen.","Bijpassende kerstoutfits & kersttruien voor het gezin |"+B,"Bijpassende kersttruien en -pyjama's voor het gezin, voor de kerstkaartfoto en kerstochtend. Rendieren, de kerstman en Noorse breisels voor volwassenen en kinderen."),
"no":("Matchende juleantrekk til familien","Matchende julegensere og julepyjamaser til hele familien, laget for julekortbilder, kvelder med juletrepynting og julemorgen. Strikk med reinsdyr, julenisse, snøfnugg og nordiske mønstre i størrelser for voksne og barn.","Matchende juleantrekk og julegensere til familien |"+B,"Matchende julegensere og julepyjamaser til familien – for julekortbilder og julemorgen. Strikk med reinsdyr, julenisse og nordiske mønstre for voksne og barn."),
"pl":("Pasujące stroje świąteczne dla całej rodziny","Pasujące do siebie świąteczne swetry i piżamy dla całej rodziny, idealne do zdjęć na kartki świąteczne, wieczorów przy ubieraniu choinki i bożonarodzeniowego poranka. Dzianiny z reniferami, Mikołajem, płatkami śniegu i motywami skandynawskimi w rozmiarach dla dorosłych i dzieci.","Pasujące stroje i swetry świąteczne dla rodziny |"+B,"Pasujące do siebie świąteczne swetry i piżamy dla rodziny, do zdjęć na kartki i na bożonarodzeniowy poranek. Renifery, Mikołaj i wzory skandynawskie dla dorosłych i dzieci."),
"pt-BR":("Looks de Natal combinando para a família","Suéteres e pijamas de Natal combinando para toda a família, feitos para as fotos do cartão de Natal, as noites de montar a árvore e a manhã de Natal. Tricôs com renas, Papai Noel, flocos de neve e estampas nórdicas em tamanhos adulto e infantil.","Looks e suéteres de Natal combinando para a família |"+B,"Suéteres e pijamas de Natal combinando para a família, para a foto do cartão e a manhã de Natal. Tricôs com renas, Papai Noel e estampas nórdicas, adulto e infantil."),
"ro":("Ținute de Crăciun asortate pentru familie","Pulovere și pijamale de Crăciun asortate pentru toată familia, create pentru fotografiile de pe felicitări, serile de împodobit bradul și dimineața de Crăciun. Tricotaje cu reni, Moș Crăciun, fulgi de nea și motive nordice, în mărimi pentru adulți și copii.","Ținute și pulovere de Crăciun asortate pentru familie |"+B,"Pulovere și pijamale de Crăciun asortate pentru familie, pentru fotografia de pe felicitare și dimineața de Crăciun. Reni, Moș Crăciun și motive nordice pentru adulți și copii."),
"ru":("Одинаковые рождественские наряды для всей семьи","Одинаковые рождественские свитеры и пижамы для всей семьи — для фото на праздничные открытки, вечеров с украшением ёлки и рождественского утра. Вязаные узоры с оленями, Санта-Клаусом, снежинками и скандинавскими мотивами в размерах для взрослых и детей.","Одинаковые рождественские наряды и свитеры для семьи |"+B,"Одинаковые рождественские свитеры и пижамы для всей семьи — для фото на открытки и рождественского утра. Олени, Санта и скандинавские узоры для взрослых и детей."),
"sv":("Matchande julkläder för familjen","Matchande jultröjor och julpyjamasar för hela familjen, gjorda för julkortsbilder, kvällar med granpynt och juldagsmorgon. Stickat med renar, tomte, snöflingor och nordiska mönster i storlekar för vuxna och barn.","Matchande julkläder och jultröjor för familjen |"+B,"Matchande jultröjor och julpyjamasar för familjen – för julkortsbilden och juldagsmorgonen. Stickat med renar, tomte och nordiska mönster för vuxna och barn."),
}
PHOTO = {
"ar":("ملابس متطابقة لصور العائلة","ملابس متناسقة لجلسات تصوير العائلة: كنزات لبطاقات عيد الميلاد، وبيجامات هالوين، وأطقم للشاطئ والحديقة والأيام العادية لجلسات الربيع والصيف. اختر مقاسًا لكل فرد من العائلة في صفحة كل منتج.","ملابس متطابقة لصور العائلة |"+B,"ملابس عائلية متناسقة لصور بطاقات عيد الميلاد وصور الخريف وجلسات الشاطئ. إطلالات متطابقة للأم والأب والأطفال بمقاس لكل فرد من العائلة."),
"cs":("Sladěné oblečení na rodinné focení","Sladěné oblečení na rodinné focení: svetry na vánoční přání, halloweenská pyžama a plážové, zahradní i každodenní soupravy pro jarní a letní focení. Na stránce každého produktu vyberete velikost pro každého člena rodiny.","Sladěné oblečení na rodinné focení |"+B,"Sladěné rodinné oblečení na fotky na vánoční přání, podzimní portréty i focení na pláži. Ladící outfity pro mámu, tátu i děti ve velikosti pro každého."),
"da":("Matchende tøj til familiefotos","Koordinerede outfits til familiefotografering: julesweatre til julekortet, halloween-pyjamas og sæt til stranden, haven og hverdagen til forårs- og sommerbilleder. Vælg en størrelse til hvert familiemedlem på hver produktside.","Matchende tøj til familiefotos |"+B,"Koordinerede familieoutfits til julekort, efterårsportrætter og strandbilleder. Matchende looks til mor, far og børn i størrelser til hvert familiemedlem."),
"de":("Passende Outfits für Familienfotos","Aufeinander abgestimmte Outfits für Familien-Fotoshootings: Pullover für die Weihnachtskarte, Halloween-Schlafanzüge sowie Strand-, Garten- und Alltagssets für Frühlings- und Sommerfotos. Auf jeder Produktseite wählen Sie die Größe für jedes Familienmitglied.","Passende Outfits für Familienfotos |"+B,"Abgestimmte Familienoutfits für Weihnachtskarten, Herbstporträts und Strandfotos. Passende Looks für Mama, Papa und Kinder in der Größe für jedes Familienmitglied."),
"el":("Ασορτί ρούχα για οικογενειακές φωτογραφίες","Συντονισμένα σύνολα για οικογενειακές φωτογραφίσεις: πουλόβερ για χριστουγεννιάτικες κάρτες, πιτζάμες Halloween και σετ για παραλία, κήπο και καθημερινές στιγμές για ανοιξιάτικες και καλοκαιρινές φωτογραφίσεις. Επιλέξτε μέγεθος για κάθε μέλος της οικογένειας στη σελίδα κάθε προϊόντος.","Ασορτί ρούχα για οικογενειακές φωτογραφίες |"+B,"Συντονισμένα οικογενειακά σύνολα για χριστουγεννιάτικες κάρτες, φθινοπωρινά πορτρέτα και φωτογραφίες στην παραλία. Ασορτί εμφανίσεις για μαμά, μπαμπά και παιδιά."),
"es":("Conjuntos a juego para fotos familiares","Conjuntos coordinados para sesiones de fotos en familia: suéteres para la postal navideña, pijamas de Halloween y conjuntos de playa, jardín y diario para sesiones de primavera y verano. Elige una talla para cada miembro de la familia en la página de cada producto.","Conjuntos a juego para fotos familiares |"+B,"Conjuntos familiares coordinados para postales navideñas, retratos de otoño y sesiones en la playa. Looks a juego para mamá, papá y niños, con talla para cada uno."),
"fi":("Yhteensopivat asut perhekuviin","Yhteensopivat asut perhekuvauksiin: neuleet joulukorttikuviin, halloween-pyjamat sekä ranta-, puutarha- ja arkiasut kevään ja kesän kuvauksiin. Valitse koko jokaiselle perheenjäsenelle kunkin tuotteen sivulla.","Yhteensopivat asut perhekuviin |"+B,"Yhteensopivat perheasut joulukortteihin, syksyn muotokuviin ja rantakuvauksiin. Samanlaiset tyylit äidille, isälle ja lapsille, koko jokaiselle perheenjäsenelle."),
"fr":("Tenues assorties pour photos de famille","Des tenues coordonnées pour vos séances photo en famille : pulls pour la carte de Noël, pyjamas d'Halloween et ensembles plage, jardin et quotidien pour les séances de printemps et d'été. Choisissez une taille pour chaque membre de la famille sur chaque page produit.","Tenues assorties pour photos de famille |"+B,"Tenues de famille coordonnées pour la carte de Noël, les portraits d'automne et les séances à la plage. Looks assortis pour maman, papa et enfants, une taille pour chacun."),
"he":("תלבושות תואמות לצילומי משפחה","תלבושות מתואמות לצילומי משפחה: סוודרים לכרטיסי ברכה לחג המולד, פיג'מות האלווין וסטים לחוף, לגינה וליום-יום לצילומי אביב וקיץ. בעמוד של כל מוצר אפשר לבחור מידה לכל אחד מבני המשפחה.","תלבושות תואמות לצילומי משפחה |"+B,"תלבושות משפחתיות מתואמות לכרטיסי ברכה לחג המולד, לצילומי סתיו ולצילומים בחוף. לוקים תואמים לאמא, לאבא ולילדים, במידה לכל אחד."),
"hi":("पारिवारिक फ़ोटो के लिए मैचिंग आउटफ़िट","फ़ैमिली फ़ोटो सेशन के लिए कोऑर्डिनेटेड आउटफ़िट: क्रिसमस कार्ड के लिए स्वेटर, हैलोवीन पजामे, और वसंत व गर्मियों के फ़ोटोशूट के लिए बीच, गार्डन और रोज़मर्रा के सेट। हर प्रोडक्ट पेज पर परिवार के हर सदस्य के लिए साइज़ चुनें।","पारिवारिक फ़ोटो के लिए मैचिंग आउटफ़िट |"+B,"क्रिसमस कार्ड, पतझड़ के पोर्ट्रेट और बीच फ़ोटोशूट के लिए कोऑर्डिनेटेड फ़ैमिली आउटफ़िट। मम्मी, पापा और बच्चों के लिए मैचिंग लुक, हर सदस्य के साइज़ में।"),
"it":("Outfit coordinati per foto di famiglia","Outfit coordinati per i servizi fotografici di famiglia: maglioni per gli auguri di Natale, pigiami di Halloween e completi da spiaggia, da giardino e per tutti i giorni per gli scatti di primavera ed estate. In ogni pagina prodotto scegli la taglia per ciascun membro della famiglia.","Outfit coordinati per foto di famiglia |"+B,"Outfit di famiglia coordinati per gli auguri di Natale, i ritratti d'autunno e le foto in spiaggia. Look abbinati per mamma, papà e bambini, con la taglia per ciascuno."),
"ja":("家族写真のためのおそろいコーデ","家族写真の撮影にぴったりなコーディネート。クリスマスカード用のセーター、ハロウィンパジャマ、春夏の撮影に合うビーチ、ガーデン、普段使いのセットがそろいます。各商品ページで家族一人ひとりのサイズをお選びください。","家族写真のためのおそろいコーデ |"+B,"クリスマスカード、秋のポートレート、ビーチでの撮影にぴったりな家族のおそろいコーデ。ママ、パパ、キッズそれぞれのサイズで選べます。"),
"ko":("가족사진을 위한 패밀리룩","가족사진 촬영을 위한 코디: 크리스마스 카드용 스웨터, 할로윈 잠옷, 봄·여름 촬영에 어울리는 해변, 가든, 데일리 세트까지. 각 상품 페이지에서 가족 구성원별로 사이즈를 선택하세요.","가족사진을 위한 패밀리룩 |"+B,"크리스마스 카드, 가을 인물 사진, 해변 촬영을 위한 가족 코디. 엄마, 아빠, 아이 모두 각자의 사이즈로 맞춰 입는 패밀리룩."),
"nl":("Bijpassende outfits voor familiefoto's","Op elkaar afgestemde outfits voor familiefotoshoots: truien voor de kerstkaart, halloweenpyjama's en strand-, tuin- en alledaagse sets voor lente- en zomershoots. Kies op elke productpagina een maat voor elk gezinslid.","Bijpassende outfits voor familiefoto's |"+B,"Afgestemde gezinsoutfits voor de kerstkaart, herfstportretten en strandshoots. Bijpassende looks voor mama, papa en kinderen, in een maat voor elk gezinslid."),
"no":("Matchende antrekk til familiebilder","Koordinerte antrekk til familiefotografering: gensere til julekortet, halloween-pyjamaser og sett til stranden, hagen og hverdagen til vår- og sommerbilder. Velg størrelse til hvert familiemedlem på hver produktside.","Matchende antrekk til familiebilder |"+B,"Koordinerte familieantrekk til julekort, høstportretter og strandbilder. Matchende looks til mamma, pappa og barn, i størrelse til hvert familiemedlem."),
"pl":("Pasujące stroje do zdjęć rodzinnych","Dopasowane stroje na rodzinne sesje zdjęciowe: swetry do zdjęć na kartki świąteczne, piżamy na Halloween oraz komplety na plażę, do ogrodu i na co dzień na wiosenne i letnie sesje. Na stronie każdego produktu wybierzesz rozmiar dla każdego członka rodziny.","Pasujące stroje do zdjęć rodzinnych |"+B,"Dopasowane rodzinne stroje do zdjęć na kartki świąteczne, jesiennych portretów i sesji na plaży. Pasujące looki dla mamy, taty i dzieci w rozmiarze dla każdego."),
"pt-BR":("Looks combinando para fotos de família","Looks coordenados para ensaios fotográficos em família: suéteres para o cartão de Natal, pijamas de Halloween e conjuntos de praia, jardim e dia a dia para ensaios de primavera e verão. Escolha um tamanho para cada membro da família na página de cada produto.","Looks combinando para fotos de família |"+B,"Looks de família coordenados para cartões de Natal, retratos de outono e ensaios na praia. Looks combinando para mamãe, papai e crianças, com tamanho para cada um."),
"ro":("Ținute asortate pentru fotografii de familie","Ținute coordonate pentru ședințele foto de familie: pulovere pentru felicitările de Crăciun, pijamale de Halloween și seturi de plajă, de grădină și de zi cu zi pentru ședințele de primăvară și vară. Alege o mărime pentru fiecare membru al familiei pe pagina fiecărui produs.","Ținute asortate pentru fotografii de familie |"+B,"Ținute de familie coordonate pentru felicitări de Crăciun, portrete de toamnă și ședințe foto la plajă. Look-uri asortate pentru mama, tata și copii, în mărimea fiecăruia."),
"ru":("Одинаковые наряды для семейной фотосессии","Согласованные образы для семейных фотосессий: свитеры для рождественских открыток, пижамы на Хэллоуин, а также комплекты для пляжа, сада и на каждый день для весенних и летних съёмок. На странице каждого товара выберите размер для каждого члена семьи.","Одинаковые наряды для семейной фотосессии |"+B,"Согласованные семейные образы для рождественских открыток, осенних портретов и съёмок на пляже. Одинаковые наряды для мамы, папы и детей в размере для каждого."),
"sv":("Matchande kläder för familjefoton","Koordinerade outfits för familjefotografering: tröjor för julkortet, halloweenpyjamasar och set för stranden, trädgården och vardagen till vår- och sommarfotograferingar. Välj en storlek för varje familjemedlem på varje produktsida.","Matchande kläder för familjefoton |"+B,"Koordinerade familjeoutfits för julkort, höstporträtt och strandfotografering. Matchande looks för mamma, pappa och barn, i storlek för varje familjemedlem."),
}
here = pathlib.Path(__file__).parent
ids = {"matching-family-christmas-outfits": "gid://shopify/Collection/363955388513",
       "family-photo-outfits": "gid://shopify/Collection/363955421281"}
out = {}
for handle, table in (("matching-family-christmas-outfits", XMAS), ("family-photo-outfits", PHOTO)):
    assert set(table) == set(D), handle
    out[handle] = {"resource_id": ids[handle], "translations": {
        loc: {"title": t, "body_html": f"<p>{b} {D[loc]}</p>", "meta_title": mt, "meta_description": md}
        for loc, (t, b, mt, md) in table.items()}}
(here / "collection_translations.json").write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
print("locales:", len(D), "values:", sum(len(v["translations"]) * 4 for v in out.values()))
