import json,html,re,hashlib
from pathlib import Path
H=Path(__file__).resolve().parent
a=json.loads((H/'source_body_context.json').read_text())
# These are source-supported concepts, not replacements to the English source.
resolved={
5:('Paisley','paisley pattern'),7:('Botanical','botanical beauty'),8:('Waist Tie','blue waist tie'),
10:('Animal print','animal print ruffle'),13:('Mothers and daughters','collection for mothers and daughters'),14:('Women and girls','Swimsuit Set for Women and Girls'),15:('Mother and daughter','Swimsuit for Mother and Daughter'),
17:('For mother and daughter','for both mother and daughter'),19:('Mother and daughter','mother and daughter'),21:('Daughter','both mother and daughter'),23:('High-waisted bottoms','High-waisted bottoms'),25:('Mother and daughter','mother and daughter two-piece swimsuits'),27:('Swimsuit Set','Mother & Daughter Matching Swimsuit Set'),28:('Two-piece swimsuit','mother and daughter matching two-piece swimsuit'),
31:('Print','unique abstract print'),32:('Floral','tropical floral print'),33:('Paisley','paisley-patterned trunks'),34:('Paradise','tropical paradise'),35:('Print','cow print swimming trunks'),
39:('Sundress','breathable sundress'),40:('Summer','Bright Summer Color'),41:('Sleeveless','sleeveless'),43:('Dresses','Dresses'),44:('Dresses','dresses'),46:('Shorts','yellow shorts'),48:('Summer dresses','flowy dresses for moms and daughters'),50:('Knitted','soft knitted fabric'),52:('Pullovers','Matching pullover sweaters'),55:('Orange','navy and orange floral design'),56:('Parents','both parents and kids'),58:('Prints','variety of vibrant prints'),60:('Sleepwear','cozy sleepwear set'),
64:('Yellow overalls and shorts','yellow overalls over a rainbow-striped tee, dad and the boys in matching yellow shorts'),65:('White shorts','matching white shorts'),67:('Gingham','gingham ruffle trim'),69:('Little Trouble','"Little Trouble" on the baby onesie'),70:('Matching','matching'),71:('T-shirt','matching T-shirt and onesie set'),73:('T-shirt','t-shirt set'),75:('Bond','special bond between father and child'),78:('Babysaurus','"Daddysaurus" and "Babysaurus"'),79:('Onesie','t-shirt and onesie options'),83:('Connection','family\'s connection'),88:('Design','"LOVE" design'),90:('For family','Family Matching T-Shirts')}
held={6:'Ch... can match chic, child or an unknown longer suffix; not uniquely recoverable.',9:'A... after Ruffle is not uniquely recoverable; body confirms ruffle detail but not missing A-word.',16:'wi... is with but missing following attribute is ambiguous.',24:'wit... is with but missing following attribute is ambiguous.',26:'Flo... absent as complete floral concept in body; body describes cover-up with whimsical pattern. Do not assert flowers.',42:'Flor... absent from body; body lists lemons, tribal designs, stripes and rainbow. Do not assert flowers.',51:'C... may mean cream/cozy/cardigan; ambiguous unfinished clause.',57:'f... may be for but intended recipient/qualifier not uniquely given.',59:'for... recipient broadlymother/daughterbody; exact unfinished qualifier unknown.',62:'S... may mean spring, summer or other; body lists both spring and summer.',63:'P... likely Perfect but missing qualification remains opaque.',72:'Quoted Wh... may describe whole pizza design but exact quoted name/print is not supplied. Do not invent a printed slogan.',77:'D... after full T-shirt Set may be Dad/design/day etc.; opaque.',85:'in... lacks location/color/style complement; not uniquely recoverable.',86:'i... lacks following complement; repeated LOVE body does not determine it.',87:'i... unresolved; body contains LOVE/heart rather than source title sun/cloud/plant design. Source contradiction needs root review.'}
rows=[]
for i,(concept,needle) in resolved.items():
 r=a[i];t=re.sub(r'\s+',' ',html.unescape(re.sub('<[^>]*>',' ',r['body']['value']))).strip()
 m=re.search(re.escape(needle),t,re.I)
 assert m,(i,needle)
 start=t.rfind('. ',0,m.start())+2 if '. ' in t[:m.start()] else 0
 end=t.find('. ',m.end());end=len(t) if end==-1 else end+1
 quote=t[start:end]
 rows.append({'productIndex':i,'resourceId':r['resourceId'],'sourceTitle':r['sourceTitle'],'resolvedConcept':concept,'supportingSourceDigests':{'body_html':r['body']['digest']},'bodyValueSHA256':hashlib.sha256(r['body']['value'].encode()).hexdigest(),'exactQuoteNormalizedWhitespace':quote,'method':'Read current English title/body; quote is body HTML visible text after entity decoding and whitespace normalization. Concept may be translated, no English source write. Full source title qualifiers must still be preserved.','review':'AUTHOR_CONTEXT_PROPOSAL_REQUIRES_INDEPENDENT_REVIEW'})
(H/'shared_source_context_resolution.json').write_text(json.dumps({'status':'BODY_BOUND_CONCEPTS_NOT_ENGLISH_SOURCE_EDITS','rows':rows,'held':[{'productIndex':i,'resourceId':a[i]['resourceId'],'sourceTitle':a[i]['sourceTitle'],'reason':reason} for i,reason in held.items()]},ensure_ascii=False,indent=2)+'\n')
print({'resolved':len(rows),'opaque':len(held)})
