#!/usr/bin/env python3
"""Generate one canonical listing runner per 2026 Christmas pajama design.

Usage: generate_runner.py tools/specs/<handle>.json
Writes ops/scripts/create-<shortcode>-<handle>.sh (SPEC + shared engine), the
single vendor image under uploads/<handle>/, and the factory size-chart image
as ops/listings/source-size-chart-<handle>.jpg.
"""
from __future__ import annotations

import json
import shutil
import sys
import urllib.request
from pathlib import Path

ROOT = Path("/Users/fsuels/Projects/dresslikemommy")
PACKET = ROOT / "dresslikemommy-growth-2026/02_AUDIT_PACKETS/2026-09-26-christmas-pajama-line"
ENGINE = PACKET / "tools/runner_engine.py"
CHART_IMAGES = {
    "factory": PACKET / "factory_size_chart_from_1073505941343.jpg",
    "line4xl": PACKET / "factory_size_chart_4xl_line_from_1080353625335.jpg",
    "zoya": PACKET / "zoya_size_chart_from_810867411211.jpg",
    "zoya_round": PACKET / "zoya_round_size_chart_from_816112676067.jpg",
    "yilin_cn": PACKET / "yilin_cn_size_charts_from_1029357235756.jpg",
    "yilin_en": PACKET / "yilin_en_size_chart_from_1072941798877.jpg",
    "shirumeng": PACKET / "shirumeng_size_chart_from_1080921462408.jpg",
    "stq_sweat": PACKET / "stq_sweatshirt_size_chart_from_1081522411618.jpg",
    "srm_cf_button": PACKET / "shirumeng_fleece_button_chart_from_1083898601268.jpg",
    "srm_cf_zip": PACKET / "shirumeng_fleece_zip_chart_from_1083898601268.jpg",
}

HEADER = """#!/usr/bin/env bash
set -euo pipefail

ROOT="/Users/fsuels/Projects/dresslikemommy"
ENV_FILE="${{SHOPIFY_ENV_FILE:-${{HOME}}/.config/dresslikemommy/shopify-admin.env}}"

# Admin tokens now come from the Dev Dashboard app and last about 24 hours.
python3 "$ROOT/ops/scripts/refresh_shopify_admin_token.py" --if-needed >/dev/null || echo "warning: token refresh failed; trying the stored token" >&2

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

: "${{SHOPIFY_STORE_DOMAIN:=dresslikemommy-com.myshopify.com}}"
: "${{SHOPIFY_ADMIN_ACCESS_TOKEN:?SHOPIFY_ADMIN_ACCESS_TOKEN not set}}"
export SHOPIFY_STORE_DOMAIN SHOPIFY_ADMIN_ACCESS_TOKEN

python3 - <<'PY'
from __future__ import annotations
import json
# Generated by {generator} from {spec_path}.
SPEC = json.loads(r'''{spec_json}''')
"""

FOOTER = """PY

if [[ "${{LISTING_PREFLIGHT_ONLY:-0}}" == "1" ]]; then
  exit 0
fi

# PROB-2026-09-25-TRANSLATION-CACHE-CONCURRENT-LOST-UPDATE: when another
# translation poller is running, create/verify the draft now and run this
# closeout later. A deferred run is NOT complete and exits 3.
if [[ "${{LISTING_DEFER_CLOSEOUT:-0}}" == "1" ]]; then
  echo "[listing-localization] DEFERRED: draft verified; closeout not run yet, listing not complete" >&2
  exit 3
fi

/usr/bin/python3 "$ROOT/ops/scripts/finalize_shopify_listing_localization.py" --handles "{handle}"
"""


def fetch_image(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0", "Referer": "https://detail.1688.com/"})
    data = urllib.request.urlopen(request, timeout=60).read()
    if len(data) < 20000:
        raise SystemExit(f"vendor image too small ({len(data)} bytes): {url}")
    dest.write_bytes(data)


def main() -> None:
    spec_path = Path(sys.argv[1]).resolve()
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    handle = spec["handle"]
    runner = ROOT / "ops/scripts" / f"create-{spec['shortcode'].lower()}-{handle}.sh"
    upload_dir = ROOT / "uploads" / handle
    image = upload_dir / spec["image_filename"]
    if not image.exists():
        fetch_image(spec["image_url"], image)
    chart = ROOT / "ops/listings" / f"source-size-chart-{handle}.jpg"
    if not chart.exists():
        shutil.copyfile(CHART_IMAGES[spec.get("chart_source", "factory")], chart)
    spec_json = json.dumps(spec, ensure_ascii=False, indent=1)
    if "'''" in spec_json:
        raise SystemExit("spec contains a triple quote")
    text = (
        HEADER.format(generator="2026-09-26-christmas-pajama-line/tools/generate_runner.py",
                      spec_path=spec_path.relative_to(ROOT), spec_json=spec_json)
        + ENGINE.read_text(encoding="utf-8")
        + FOOTER.format(handle=handle)
    )
    runner.write_text(text, encoding="utf-8")
    runner.chmod(0o755)
    print(runner)


if __name__ == "__main__":
    main()
