#!/usr/bin/env python3
"""Sanitized read-only GA4 UI network probe.

The probe watches response bodies generated by GA4 report navigation through the
existing logged-in Chrome DevTools session. It stores only sanitized metadata and
short redacted context snippets around relevant non-US candidate patterns.
"""

from __future__ import annotations

import argparse
import json
import re
import time
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import websocket


DEFAULT_CDP_PORT = 9222
DEFAULT_OUTPUT_DIR = Path("dresslikemommy-growth-2026/02_AUDIT_PACKETS/2026-05-12-paid-growth-measurement-safe-lanes/ga4_readonly_probe")
GA4_EVENTS_URL = "https://analytics.google.com/analytics/web/#/a88409806p330266838/reports/explorer?params=_r.explorerCard..selmet%3D%5B%22eventCount%22%2C%22totalRevenue%22%5D%26_r.explorerCard..seldim%3D%5B%22eventName%22%5D%26_r.explorerCard..startRow%3D10&r=top-events"

PATTERNS = [
    "purchase",
    "transaction",
    "transactionId",
    "transaction_id",
    "currency",
    "DKK",
    "GBP",
    "CHF",
    "201",
    "434",
    "259",
    "427",
    "24",
    "34",
]


class CdpClient:
    def __init__(self, websocket_url: str) -> None:
        self.ws = websocket.create_connection(websocket_url, timeout=30, suppress_origin=True)
        self.next_id = 1

    def close(self) -> None:
        self.ws.close()

    def call(self, method: str, params: dict[str, Any] | None = None, timeout_seconds: int = 30) -> dict[str, Any]:
        message_id = self.next_id
        self.next_id += 1
        self.ws.send(json.dumps({"id": message_id, "method": method, "params": params or {}}))
        start = time.time()
        while time.time() - start < timeout_seconds:
            event = json.loads(self.ws.recv())
            if event.get("id") == message_id:
                return event
            if method == "__poll__":
                return event
        raise TimeoutError(f"Timed out waiting for CDP response {message_id} ({method})")

    def recv_event(self, timeout_seconds: int = 1) -> dict[str, Any] | None:
        old_timeout = self.ws.gettimeout()
        self.ws.settimeout(timeout_seconds)
        try:
            return json.loads(self.ws.recv())
        except Exception:
            return None
        finally:
            self.ws.settimeout(old_timeout)


def get_json(url: str) -> Any:
    with urllib.request.urlopen(url, timeout=10) as response:
        return json.loads(response.read().decode("utf-8"))


def open_page(cdp_port: int, url: str) -> dict[str, Any]:
    encoded = urllib.parse.quote(url, safe="")
    request = urllib.request.Request(f"http://127.0.0.1:{cdp_port}/json/new?{encoded}", method="PUT")
    with urllib.request.urlopen(request, timeout=10) as response:
        return json.loads(response.read().decode("utf-8"))


def find_or_open_ga4_page(cdp_port: int) -> dict[str, Any]:
    pages = get_json(f"http://127.0.0.1:{cdp_port}/json/list")
    for page in pages:
        if page.get("type") == "page" and "analytics.google.com/analytics/web" in page.get("url", ""):
            return page
    return open_page(cdp_port, GA4_EVENTS_URL)


def evaluate(client: CdpClient, expression: str) -> Any:
    result = client.call("Runtime.evaluate", {"expression": expression, "awaitPromise": True, "returnByValue": True})
    return result.get("result", {}).get("result", {}).get("value")


def sanitize_snippet(text: str, pattern: str) -> str:
    match = re.search(re.escape(pattern), text, re.I)
    if not match:
        return ""
    start = max(0, match.start() - 160)
    end = min(len(text), match.end() + 160)
    snippet = re.sub(r"\s+", " ", text[start:end])
    snippet = re.sub(r"[\w.+-]+@[\w.-]+", "[redacted-email]", snippet)
    snippet = re.sub(r"\b\d{5,}\b", "[redacted-number]", snippet)
    return snippet[:360]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cdp-port", type=int, default=DEFAULT_CDP_PORT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--seconds", type=int, default=35)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    page = find_or_open_ga4_page(args.cdp_port)
    client = CdpClient(page["webSocketDebuggerUrl"])
    request_urls: dict[str, str] = {}
    findings: list[dict[str, Any]] = []
    errors: list[str] = []
    try:
        client.call("Page.enable")
        client.call("Network.enable")
        client.call("Network.setCacheDisabled", {"cacheDisabled": True})
        client.call("Page.navigate", {"url": GA4_EVENTS_URL})
        start = time.time()
        while time.time() - start < args.seconds:
            event = client.recv_event(timeout_seconds=1)
            if not event:
                continue
            method = event.get("method")
            params = event.get("params", {})
            if method == "Network.requestWillBeSent":
                request = params.get("request", {})
                request_urls[params.get("requestId", "")] = request.get("url", "")
            elif method == "Network.responseReceived":
                request_id = params.get("requestId")
                response = params.get("response", {})
                url = response.get("url", request_urls.get(request_id, ""))
                if not any(host in url for host in ("analytics.google.com", "google.com/analytics", "analyticsdata")):
                    continue
                try:
                    body_result = client.call("Network.getResponseBody", {"requestId": request_id}, timeout_seconds=5)
                    body = body_result.get("result", {}).get("body", "")
                except Exception as exc:
                    errors.append(f"{url[:120]} :: {type(exc).__name__}")
                    continue
                haystack = body[:200000]
                hits = [pattern for pattern in PATTERNS if re.search(re.escape(pattern), haystack, re.I)]
                if hits:
                    findings.append({
                        "url_host_path": re.sub(r"https?://([^/?#]+).*", r"\1", url),
                        "url_contains": {
                            "analytics": "analytics" in url,
                            "batchexecute": "batchexecute" in url,
                            "report": "report" in url.lower(),
                        },
                        "body_length": len(body),
                        "hits": hits,
                        "snippets": {pattern: sanitize_snippet(haystack, pattern) for pattern in hits[:8]},
                    })
        body_text = evaluate(client, "document.body ? document.body.innerText : ''") or ""
        summary = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "mode": "GA4_UI_NETWORK_SANITIZED_READONLY_PROBE",
            "guardrail": "Read-only GA4 report navigation and response inspection only; stored findings are sanitized snippets, not raw response bodies.",
            "current_url": evaluate(client, "location.href"),
            "title": evaluate(client, "document.title"),
            "visible_purchase": "purchase" in body_text.lower(),
            "visible_candidate_hits": [pattern for pattern in PATTERNS if re.search(re.escape(pattern), body_text, re.I)],
            "network_finding_count": len(findings),
            "network_findings": findings[:30],
            "response_body_errors_sample": errors[:20],
        }
        output = args.output_dir / "ga4_network_sanitized_probe_summary.json"
        output.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(summary, ensure_ascii=False, indent=2)[:8000])
    finally:
        client.close()


if __name__ == "__main__":
    main()
