from pathlib import Path
import json,hashlib,collections
P=Path(__file__).parent;PACK=P.parents[2]
read=lambda n:json.loads((P/n).read_text())
fsha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
write=lambda n,d:(P/n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
coverage=read('prepared_coverage.json');short=read('short_candidates.json')['rows'];bodies=read('body_candidates.json')['rows'];other=read('other_body_worklist.json')['rows'];ledger=json.loads((PACK/'articles/defect_ledger.json').read_text());rows=coverage['rows'].copy()
# Key selection remains unchanged. Record latest reviewed correction variants too.
hefile=PACK/'root-bodies/de/he_candidate_corrections.json';he=json.loads(hefile.read_text())['rows'];hekeys={(r['resourceId'],r['locale'],r['key'])for r in he}
defile=PACK/'root-bodies/he-pl/de_independent_review.json';de=json.loads(defile.read_text())['corrections'];deby={(r['resourceId'],r['locale'],r['key']):r for r in de}
for r in rows:
 k=(r['resourceId'],r['locale'],r['key'])
 if k in hekeys:r['candidateFile']=str(hefile.relative_to(PACK));r['candidateFileSHA256']=fsha(hefile)
 if k in deby:r['latestCorrectionReview']=str(defile.relative_to(PACK));r['latestCorrectionReviewSHA256']=fsha(defile);r['reviewedCorrectedValueSHA256']=deby[k]['proposedValueSHA256']
for r in short+bodies:
 isshort=r['key']!='body_html';hold=isshort and r['ledgerId']in{'809','5097'}
 out={'id':r['ledgerId'],'resourceId':r['resourceId'],'locale':r['locale'],'key':r['key'],'flags':r['flags'],'sourceDigest':r['sourceDigest'],'sourceSHA256':r['sourceSHA256'],'beforeSHA256':r['expectedBeforeValueSHA256'],'valueSHA256':r['valueSHA256'],'candidateFile':str((P/('short_candidates.json'if isshort else'body_candidates.json')).relative_to(PACK)),'candidateFileSHA256':fsha(P/('short_candidates.json'if isshort else'body_candidates.json')),'disposition':'CONFIRMED_DEFECT_CORRECTION_PREPARED','rootReviewStatus':('EXISTING_SOURCE_CLAIM_QUESTION_PENDING'if hold else'APPROVED_WITH_LISTED_SWIMWORD_CORRECTIONS'if isshort else'INDEPENDENT_REVIEW_REQUESTED')}
 if r['ledgerId']=='730':out['disposition']='STALE_FLAG_MEANING_EQUIVALENT_GRAMMAR_REPAIR_PREPARED';out['note']='Existing title already conveyed current Halloween-family-costume meaning. Grammar/compound repair prepared and root approved; no semantic source drift claimed.'
 if hold:out['note']='Root identified this existing English source free-shipping-over-$50 question as pending. This packet creates no new approval gate or English source change.'
 if isshort and r['locale']=='de'and r['sourceValue']=='Mother-Daughter Matching Swimsuits Complete Guide for Summer':out['rootReviewedReplacement']='Passende Bademode für Mutter und Tochter: der komplette Sommer-Ratgeber'
 if isshort and r['locale']=='de'and r['sourceValue']=='Best Matching Swimsuits for the Whole Family':out['rootReviewedReplacement']='Die beste passende Bademode für die ganze Familie'
 if isshort and r['locale']=='nl'and r['sourceValue']=='Mother-Daughter Matching Swimsuits Complete Guide for Summer':out['rootReviewedReplacement']='Bijpassende badkleding voor moeder en dochter: complete gids voor de zomer'
 rows.append(out)
for r in other:rows.append({'id':r['ledgerId'],'resourceId':r['resourceId'],'locale':r['locale'],'key':r['key'],'flags':r['flags'],'sourceDigest':r['sourceDigest'],'rawFile':r['rawFile'],'rawFileSHA256':r['rawFileSHA256'],'disposition':'ASSIGNED_FULL_BODY_REVIEW_PENDING','owner':'/root/product_release_review','worklist':str((P/'other_body_worklist.json').relative_to(PACK)),'expectedOutputDirectory':'review/other-article-bodies/'})
# Integrate the sibling completion only after an explicit returned artifact is available.
ids={r['id']for r in rows};assert len(ids)==len(rows)==499;assert ids=={r['id']for r in ledger}
keys={(r['resourceId'],r['locale'],r['key'])for r in rows};assert len(keys)==499
rows.sort(key=lambda r:int(r['id']))
counts=collections.Counter(r['disposition']for r in rows)
summary={'status':'ALL_499_FLAGS_RECONCILED_16_FULL_BODY_REVIEWS_IN_PROGRESS','ledgerRows':499,'publishedNonEnglishLocaleCount':20,'preparedPreviously':368,'newPreparedShortFields':52,'newPreparedBodies':63,'newPreparedTotal':115,'remainingSiblingBodyReview':16,'rootApprovedShortFields':50,'rootExistingSourceQuestionShortFields':2,'staleMeaningEquivalentFlags':1,'noChangeFalsePositiveDispositions':0,'counts':dict(counts),'rows':rows,'scope':'Coverage and translation-candidate reconciliation only; never a claim all fields are currently live. Root owns guards, application, Git main synchronization and public verification.','countsByLocale':{loc:{'allFlags':sum(x['locale']==loc for x in rows),'alreadyPrepared':sum(x['locale']==loc and x['disposition']=='ALREADY_PREPARED_EXACT_KEY'for x in rows),'newPrepared':sum(x['locale']==loc and x['disposition']in{'CONFIRMED_DEFECT_CORRECTION_PREPARED','STALE_FLAG_MEANING_EQUIVALENT_GRAMMAR_REPAIR_PREPARED'}for x in rows),'siblingReviewPending':sum(x['locale']==loc and x['disposition']=='ASSIGNED_FULL_BODY_REVIEW_PENDING'for x in rows)}for loc in coverage['publishedNonEnglishLocales']}}
write('all_499_reconciliation.json',summary)
review={'status':'OWNED_115_FIELDS_PREPARED_FOR_ROOT_REVIEW','scope':'52 short fields and63 ar/cs/da template bodies','shortRows':52,'bodyRows':63,'bodyLocales':{'ar':21,'cs':21,'da':21},'uniqueBodyVisibleSourceTargetPairsRead':837,'uniqueImageAltPairsRead':335,'bodySourceRawDigestBeforeBindings':'PASS','bodyNumbersUnitsLinksTablesMarkup':'PASS_WITH_INDIVIDUALLY_REVIEWED_LOCALIZED_ALT_STRINGS','beforeSnapshot':'All rows retain exact raw before object/value and outdated state; current live guard required.','authorReview':'All unique body text pairs read in full, then all unique image-alt pairs; every changed visible fragment reviewed in context. Full current source wording and complete paragraph/list structure retained. Repeated clauses reused only after exact source and target comparison.','correctionClasses':['Current source all-orders shipping wording replaces old over-$50 conditions in63 bodies. This is faithful translation of the existing source, not a new shipping-policy decision.','Restore source-named garment features and missing product description words.','Translate ordinary retained English descriptors while preserving printed slogans and product/brand identifiers.','Correct modifier attachment, agreement and inline phrase grammar.','Preserve source CTA arrows and every numeric value; retain incomplete source product-label fragments rather than inventing unseen suffixes.','Correct translation-created quote escaping in image-alt values. Keep12 inherited malformed English-source image tag occurrences exactly except their parsed alt value.'],'sourceMalformedMarkup':'See inherited_source_img_markup.json; source-owned English markup issue recorded, not a newly invented release hold.','shortRootReview':'Root approved50 subject to three specific generic-swimwear wording corrections; DE/SV Valentine meta await the already-open source shipping question. Frozen author file retained.','externalWrites':False,'originalCandidatesModified':False,'all499Ledger':'all_499_reconciliation.json'}
write('AUTHOR_REVIEW.json',review)
files=['short_candidates.json','short_checks.json','body_candidates.json','body_checks.json','body_changes.json','AUTHOR_REVIEW.json','all_499_reconciliation.json','other_body_worklist.json','prepared_coverage.json','inherited_source_img_markup.json']
write('MANIFEST.json',{'status':'OWNED_115_FIELDS_FROZEN_FOR_ROOT_REVIEW','files':[{'file':f,'SHA256':fsha(P/f)}for f in files],'pendingSiblingBodyRows':16})
print({'reconciled':len(rows),'prepared':483,'pendingSibling':16,'counts':dict(counts)})
