#!/usr/bin/env python3
from manual_repairs import put,source,edits,HERE
import json

dad={
'ar':['قمصان للأب والطفل','تسوق قمصانًا بأزرار للأب والطفل، وقمصان هاواي، وقطعًا علوية أنيقة ومتناسقة للأب والابن، للعطلات والصور العائلية والنزهات الصيفية.','قمصان الأب والطفل — قمصان بأزرار متناسقة للأب والابن','تسوق قمصان الأب والطفل وقمصانًا بأزرار متناسقة للأب والابن، بما فيها تصاميم هاواي والتصاميم الاستوائية للعطلات والصور العائلية وأيام الصيف.'],
'cs':['Košile pro tatínka a dítě','Nakupujte košile na knoflíky pro tatínka a dítě, havajské košile a elegantní sladěné topy pro otce a syna na dovolenou, rodinné focení a letní výlety.','Košile pro tatínka a dítě — sladěné košile na knoflíky pro otce a syna','Nakupujte košile pro tatínka a dítě a sladěné košile na knoflíky pro otce a syna, včetně havajských a tropických stylů na dovolenou, rodinné focení a letní dny.'],
'de':['Hemden für Papa und Kind','Entdecken Sie Hemden mit Knopfleiste für Papa und Kind, Hawaiihemden und stilvolle Vater-Sohn-Oberteile im Partnerlook für Urlaub, Familienfotos und sommerliche Ausflüge.','Hemden für Papa und Kind — Vater-Sohn-Hemden im Partnerlook','Entdecken Sie Hemden für Papa und Kind sowie aufeinander abgestimmte Vater-Sohn-Hemden mit Knopfleiste, darunter Hawaii- und Tropenmuster für Urlaub, Familienfotos und Sommertage.'],
'el':['Πουκάμισα για μπαμπά και παιδί','Αγοράστε πουκάμισα με κουμπιά για μπαμπά και παιδί, χαβανέζικα πουκάμισα και κομψά ασορτί τοπ για πατέρα και γιο, για διακοπές, οικογενειακές φωτογραφίες και καλοκαιρινές εξόδους.','Πουκάμισα για μπαμπά και παιδί — ασορτί πουκάμισα με κουμπιά για πατέρα και γιο','Αγοράστε πουκάμισα για μπαμπά και παιδί και ασορτί πουκάμισα με κουμπιά για πατέρα και γιο, με χαβανέζικα και τροπικά σχέδια για διακοπές, οικογενειακές φωτογραφίες και καλοκαιρινές ημέρες.'],
'es':['Camisas para papá y peque','Compra camisas con botones para papá y peque, camisas hawaianas y prendas superiores elegantes a juego para padre e hijo, para vacaciones, fotos familiares y salidas de verano.','Camisas para papá y peque — camisas con botones a juego para padre e hijo','Compra camisas para papá y peque y camisas con botones a juego para padre e hijo, con estilos hawaianos y tropicales para vacaciones, fotos familiares y días de verano.'],
'fi':['Isän ja lapsen paidat','Osta isän ja lapsen napitettavia paitoja, havaijipaitoja ja tyylikkäitä yhteensopivia isän ja pojan yläosia lomille, perhekuviin ja kesäretkille.','Isän ja lapsen paidat — yhteensopivat napitettavat paidat isälle ja pojalle','Osta isän ja lapsen paitoja sekä yhteensopivia napitettavia paitoja isälle ja pojalle, mukaan lukien havaiji- ja trooppiset tyylit lomille, perhekuviin ja kesäpäiviin.'],
'fr':['Chemises papa et enfant','Découvrez les chemises boutonnées papa et enfant, les chemises hawaïennes et les hauts élégants assortis père-fils pour les vacances, les photos de famille et les sorties d’été.','Chemises papa et enfant — chemises boutonnées assorties père-fils','Découvrez les chemises papa et enfant et les chemises boutonnées assorties père-fils, avec des styles hawaïens et tropicaux pour les vacances, les photos de famille et les journées d’été.'],
'hi':['पिता और बच्चे के लिए शर्ट','छुट्टियों, पारिवारिक तस्वीरों और गर्मियों की सैर के लिए पिता और बच्चे की बटन वाली शर्ट, हवाईयन शर्ट और पिता-पुत्र के लिए आकर्षक मेल खाते ऊपरी परिधान खरीदें।','पिता और बच्चे की शर्ट — पिता-पुत्र के लिए मेल खाती बटन वाली शर्ट','पिता और बच्चे की शर्ट और पिता-पुत्र के लिए मेल खाती बटन वाली शर्ट खरीदें, जिनमें छुट्टियों, पारिवारिक तस्वीरों और गर्मियों के दिनों के लिए हवाईयन और ट्रॉपिकल डिज़ाइन शामिल हैं।'],
'it':['Camicie papà e bambino','Acquista camicie con bottoni papà e bambino, camicie hawaiane e raffinati capi coordinati per la parte superiore dell’abbigliamento di padre e figlio, per vacanze, foto di famiglia e uscite estive.','Camicie papà e bambino — camicie con bottoni coordinate padre e figlio','Acquista camicie papà e bambino e camicie con bottoni coordinate padre e figlio, con stili hawaiani e tropicali per vacanze, foto di famiglia e giornate estive.'],
'ja':['パパと子どものシャツ','休暇、家族写真、夏のお出かけに。パパと子どもの前開きシャツ、アロハシャツ、父と息子でそろえられる上品なトップスをご覧ください。','パパと子どものシャツ — 父と息子のおそろい前開きシャツ','パパと子どものシャツや、父と息子のおそろい前開きシャツをご覧ください。休暇、家族写真、夏の日にぴったりのハワイアン柄やトロピカル柄もそろっています。'],
'nl':['Overhemden voor vader en kind','Shop overhemden met knopen voor vader en kind, Hawaïaanse overhemden en stijlvolle bijpassende vader-zoontops voor vakanties, gezinsfoto’s en zomerse uitstapjes.','Overhemden voor vader en kind — bijpassende vader-zoonoverhemden met knopen','Shop overhemden voor vader en kind en bijpassende vader-zoonoverhemden met knopen, met Hawaïaanse en tropische stijlen voor vakanties, gezinsfoto’s en zomerdagen.'],
'no':['Skjorter til pappa og barn','Kjøp skjorter med knapper til pappa og barn, hawaiiskjorter og stilfulle matchende overdeler til far og sønn for ferier, familiebilder og sommerutflukter.','Skjorter til pappa og barn — matchende skjorter med knapper til far og sønn','Kjøp skjorter til pappa og barn og matchende skjorter med knapper til far og sønn, inkludert hawaiiske og tropiske stiler til ferier, familiebilder og sommerdager.'],
'pl':['Koszule dla taty i dziecka','Kup koszule zapinane na guziki dla taty i dziecka, koszule hawajskie oraz eleganckie, dopasowane górne części garderoby dla ojca i syna na wakacje, rodzinne zdjęcia i letnie wyjścia.','Koszule dla taty i dziecka — dopasowane koszule na guziki dla ojca i syna','Kup koszule dla taty i dziecka oraz dopasowane koszule na guziki dla ojca i syna, w tym wzory hawajskie i tropikalne na wakacje, rodzinne zdjęcia i letnie dni.'],
'pt-BR':['Camisas para pai e criança','Compre camisas com botões para pai e criança, camisas havaianas e peças elegantes para a parte de cima combinando para pai e filho, para férias, fotos de família e passeios de verão.','Camisas para pai e criança — camisas com botões combinando para pai e filho','Compre camisas para pai e criança e camisas com botões combinando para pai e filho, com estilos havaianos e tropicais para férias, fotos de família e dias de verão.'],
'ro':['Cămăși pentru tată și copil','Cumpără cămăși cu nasturi pentru tată și copil, cămăși hawaiiene și topuri elegante asortate pentru tată și fiu, pentru vacanțe, fotografii de familie și ieșiri de vară.','Cămăși pentru tată și copil — cămăși cu nasturi asortate pentru tată și fiu','Cumpără cămăși pentru tată și copil și cămăși cu nasturi asortate pentru tată și fiu, inclusiv stiluri hawaiiene și tropicale pentru vacanțe, fotografii de familie și zile de vară.'],
'ru':['Рубашки для папы и ребёнка','Выбирайте рубашки на пуговицах для папы и ребёнка, гавайские рубашки и элегантные верхи в едином стиле для отца и сына — для отпуска, семейных фотографий и летних прогулок.','Рубашки для папы и ребёнка — рубашки на пуговицах в едином стиле для отца и сына','Выбирайте рубашки для папы и ребёнка и рубашки на пуговицах в едином стиле для отца и сына, включая гавайские и тропические модели для отпуска, семейных фотографий и летних дней.'],
'sv':['Skjortor för pappa och barn','Handla skjortor med knappar för pappa och barn, Hawaiiskjortor och stilrena matchande överdelar för far och son till semestrar, familjefoton och sommarutflykter.','Skjortor för pappa och barn — matchande skjortor med knappar för far och son','Handla skjortor för pappa och barn och matchande skjortor med knappar för far och son, med hawaiiska och tropiska stilar för semestrar, familjefoton och sommardagar.']}
dad_sources=['Daddy & Me Shirts',source('<p>Shop Daddy &amp;'),'Daddy & Me Shirts — Matching Father & Son Button-Downs',source('Shop Daddy & Me shirts and')]
for l,vs in dad.items():
    for idx,(s,v) in enumerate(zip(dad_sources,vs)):put(l,s,'<p>'+v+'</p>' if idx==1 else v)

# Retain all six exact link destinations and their category meaning.
paths=['/collections/matching-family-vacation-outfits','/collections/family-swimsuits','/collections/pajamas','/collections/new-women-outfits','/collections/formal-dresses','/collections/daddy-me-shirts']
footer={
'ar':(['ملابس عائلية متناسقة للعطلات','ملابس سباحة شاطئية متناسقة','بيجامات للأم والطفل','ملابس عائلية متناسقة','فساتين للأم والابنة لحضور حفلات الزفاف','قمصان للأب والطفل'],'<p>هل تخطط لاختيار {0} أو لتشكيلة من {1}؟ ابدأ بأطقم عائلية وإطلالات سباحة متناسقة تجمع أفراد العائلة ضمن لوحة ألوان واحدة واضحة.</p><p>هل تبحث عن {2}، أو {3}، أو {4}، أو {5}؟ ابدأ بالفئة أولًا، ثم حدد التشكيلة المناسبة للمناسبة.</p>'),
'cs':(['sladěného rodinného oblečení na dovolenou','sladěných plavek na pláž','pyžama pro maminku a dítě','sladěné rodinné oblečení','šaty pro maminku a dceru jako svatební hosty','košile pro tatínka a dítě'],'<p>Plánujete výběr {0} nebo kolekci {1}? Začněte sladěnými rodinnými soupravami a plavkami, které celou skupinu spojí v jedné ucelené barevné paletě.</p><p>Hledáte {2}, {3}, {4} nebo {5}? Začněte kategorií a poté výběr zúžte na kolekci vhodnou pro danou příležitost.</p>'),
'de':(['Partnerlooks für den Familienurlaub','aufeinander abgestimmter Bademode für den Strand','Mama-und-Kind-Pyjamas','Partnerlooks für die Familie','Hochzeitsgastkleidern für Mutter und Tochter','Papa-und-Kind-Hemden'],'<p>Planen Sie eine Auswahl an {0} oder eine Kollektion {1}? Beginnen Sie mit abgestimmten Familien-Sets und Bade-Looks, die alle in einer gemeinsamen Farbpalette verbinden.</p><p>Suchen Sie nach {2}, {3}, {4} oder {5}? Wählen Sie zuerst die Kategorie und grenzen Sie die Auswahl dann auf die Kollektion ein, die zum Anlass passt.</p>'),
'el':(['ασορτί οικογενειακά ρούχα διακοπών','ασορτί μαγιό για την παραλία','πιτζάμες για μαμά και παιδί','ασορτί οικογενειακά ρούχα','φορέματα για μαμά και κόρη ως καλεσμένες σε γάμο','πουκάμισα για μπαμπά και παιδί'],'<p>Σχεδιάζετε μια επιλογή από {0} ή μια συλλογή με {1}; Ξεκινήστε με συντονισμένα οικογενειακά σετ και εμφανίσεις παραλίας που κρατούν όλη την παρέα σε μία ενιαία χρωματική παλέτα.</p><p>Ψάχνετε {2}, {3}, {4} ή {5}; Ξεκινήστε από την κατηγορία και έπειτα περιορίστε την επιλογή στη συλλογή που ταιριάζει στην περίσταση.</p>'),
'fi':(['yhteensopivia perheen loma-asuja','yhteensopivia uima-asuja rannalle','äidin ja lapsen pyjamia','yhteensopivia perheasuja','äidin ja tyttären mekkoja häävieraille','isän ja lapsen paitoja'],'<p>Suunnitteletko valikoimaa, jossa on {0}, tai kokoelmaa, jossa on {1}? Aloita yhteensopivista perheseteistä ja uima-asuista, jotka yhdistävät koko ryhmän yhteen selkeään värimaailmaan.</p><p>Etsitkö {2}, {3}, {4} tai {5}? Aloita tuoteryhmästä ja rajaa sen jälkeen valinta tilaisuuteen sopivaan kokoelmaan.</p>'),
'hi':(['परिवार के लिए मेल खाते छुट्टियों के परिधान','मेल खाते बीच स्विमसूट','माँ और बच्चे के पजामे','परिवार के मेल खाते परिधान','शादी में मेहमान के रूप में पहनने के लिए माँ-बेटी की ड्रेस','पिता और बच्चे की शर्ट'],'<p>क्या आप {0} का चयन या {1} का संग्रह तैयार कर रहे हैं? परिवार के मेल खाते सेट और तैराकी के परिधानों से शुरुआत करें, जो पूरे समूह को एक स्पष्ट रंग-संयोजन में रखते हैं।</p><p>क्या आप {2}, {3}, {4} या {5} खरीद रहे हैं? पहले श्रेणी चुनें, फिर उस संग्रह तक विकल्प सीमित करें जो इस अवसर के अनुकूल हो।</p>'),
'ja':(['家族のおそろいのバケーションウェア','ビーチ用のおそろい水着','ママと子どものパジャマ','家族のおそろい服','結婚式に参列する母娘のドレス','パパと子どものシャツ'],'<p>{0}のセレクションや{1}のコレクションをお考えですか？まずは、家族みんなの色合いを一つにまとめる、おそろいのセットや水着からお選びください。</p><p>{2}、{3}、{4}、{5}をお探しですか？最初にカテゴリーを選び、そのシーンに合うコレクションへ絞り込んでみてください。</p>'),
'ro':(['ținute asortate pentru vacanța în familie','costume de baie asortate pentru plajă','pijamale pentru mamă și copil','ținute asortate pentru familie','rochii pentru mamă și fiică invitate la nuntă','cămăși pentru tată și copil'],'<p>Pregătești o selecție de {0} sau o colecție de {1}? Începe cu seturi coordonate pentru familie și ținute de înot care păstrează întregul grup într-o paletă cromatică unitară.</p><p>Cauți {2}, {3}, {4} sau {5}? Începe cu categoria, apoi restrânge alegerea la colecția potrivită momentului.</p>'),
'sv':(['matchande kläder för familjesemestern','matchande badkläder för stranden','pyjamasar för mamma och barn','matchande familjekläder','klänningar för mamma och dotter som bröllopsgäster','skjortor för pappa och barn'],'<p>Planerar du ett urval av {0} eller en kollektion med {1}? Börja med samordnade familjeset och badkläder som samlar hela gruppen i en tydlig gemensam färgskala.</p><p>Letar du efter {2}, {3}, {4} eller {5}? Börja med kategorin och välj sedan den kollektion som passar tillfället.</p>')}
footer_source=source('<p>Planning a <a')
for l,(labels,template) in footer.items():
    anchors=[f'<a href="{path}">{label}</a>' for path,label in zip(paths,labels)]
    put(l,footer_source,template.format(*anchors))

if __name__=='__main__':
    (HERE/'manual_collections_footer_log.json').write_text(json.dumps(edits,ensure_ascii=False,indent=2)+'\n')
    print('Local collection/footer corrections:',len(edits))
